// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: internal/imagepuller/imagepuller.proto
package imagepuller

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type ImagePullerService interface {
	PullImage(context.Context, *ImagePullRequest) (*ImagePullResponse, error)
}

func RegisterImagePullerService(srv *ttrpc.Server, svc ImagePullerService) {
	srv.RegisterService("edgelesssys.contrast.imagepuller.ImagePuller", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"PullImage": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ImagePullRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.PullImage(ctx, &req)
			},
		},
	})
}

type imagepullerClient struct {
	client *ttrpc.Client
}

func NewImagePullerClient(client *ttrpc.Client) ImagePullerService {
	return &imagepullerClient{
		client: client,
	}
}

func (c *imagepullerClient) PullImage(ctx context.Context, req *ImagePullRequest) (*ImagePullResponse, error) {
	var resp ImagePullResponse
	if err := c.client.Call(ctx, "edgelesssys.contrast.imagepuller.ImagePuller", "PullImage", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
