// Copyright 2025 Edgeless Systems GmbH
// SPDX-License-Identifier: BUSL-1.1

package tdx

import (
	"encoding/hex"
	"testing"

	"github.com/google/go-tdx-guest/proto/tdx"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/encoding/protojson"
)

func TestGetPIID(t *testing.T) {
	require := require.New(t)
	expectedPIID, err := hex.DecodeString("e90210702a2cc5ad9764f29ddc8fde8c")
	require.NoError(err)

	var quote tdx.QuoteV4
	require.NoError(protojson.Unmarshal([]byte(quoteJSON), &quote))

	piid, err := getPIID(&quote)
	require.NoError(err)
	require.Equal(expectedPIID, piid)
}

var quoteJSON = `
{
  "header": {
    "version": 4,
    "attestationKeyType": 2,
    "teeType": 129,
    "qeSvn": "AAA=",
    "pceSvn": "AAA=",
    "qeVendorId": "k5pyM/ecTKmUCg2zlX8GBw==",
    "userData": "aifPiUc3iQzI+/BSr8LHuwAAAAA="
  },
  "tdQuoteBody": {
    "teeTcbSvn": "CwEDAAAAAAAAAAAAAAAAAA==",
    "mrSeam": "e/BjKA6U+wUfXdex/FnOmqxCu5Yd+NRLcJybD/h6e032SGV7ptEYlYn+qx1aPJqd",
    "mrSignerSeam": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "seamAttributes": "AAAAAAAAAAA=",
    "tdAttributes": "AAAAEAAAAAA=",
    "xfam": "5wIGAAAAAAA=",
    "mrTd": "shtXCXqX9eK5VGa92xI/5RHkKEu4nQ64eu6K2cmNcQSW1VWp45dscnZBG6ysaOiz",
    "mrConfigId": "P5mnfhRbQ1+Ux4cGyWRjQAbIBdGKXUYI7JfAut0WlZoAAAAAAAAAAAAAAAAAAAAA",
    "mrOwner": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "mrOwnerConfig": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "rtmrs": [
      "Mgd+mhvgST0glyoDp8I3z3maYTou0iKm6DXg32+Tfv2Mnf8X0f9wjowyAQ5pJ5eF",
      "jIR+RKslaiAdHqZDogr3ghnIrIPrf+BRa5PzXdAtEMMxzYGU8c4ZHPi+gsNq1mb/",
      "tyq3t5hRjHcGiiapLB4lowG33G7hw8U3Tqo+ddC3JLaE6gLFtzlbjZVb591PwcgT",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    ],
    "reportData": "OcniscPw6qd0fx2iBdROAm+dDfvqvEewUCiC4tVoujuXego3LTsgjSuQt0u5/WsC8TxfljTKKuHcerZDTqkS2Q=="
  },
  "signedDataSize": 4300,
  "signedData": {
    "signature": "akQIWDu4ymFPIkT1bjaSUR8Jp9ZQdbtiOClI3dsJq449WfNki5fqLjLpyLgx2onQo8/5WiG0YljSB0KQwPcezw==",
    "ecdsaAttestationKey": "VWjTE4kg+v/NWrCQ6qavh2hwLU5zqsnsfzRzz+Us9EDCGIVAhPzltGUT5/j/Z9cAT/zoKDQiwz/l6By7XhctKQ==",
    "certificationData": {
      "certificateDataType": 6,
      "size": 4166,
      "qeReportCertificationData": {
        "qeReport": {
          "cpuSvn": "AwMZGwT/AAYAAAAAAAAAAA==",
          "reserved1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
          "attributes": "FQAAAAAAAADnAAAAAAAAAA==",
          "mrEnclave": "5aOntdgwwpU7mFNMbFmjo0/cNOkz9/WJjwqFzwiEa8o=",
          "reserved2": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
          "mrSigner": "3J4qfG+UjxdHTjSn/EPtAw98FWPxur3fY0DILg5UqMU=",
          "reserved3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "isvProdId": 2,
          "isvSvn": 6,
          "reserved4": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "reportData": "Ib33ACySTNEtXoIYC0b94aBcYKz7oTT/fGVy6GdQi/EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        },
        "qeReportSignature": "XWjIFgVe4a7357GxZYmkMbFzF2jGmHVlYivNOoGDVWoZ4oOBBlg31B2Rzaa/5w0JTitvYILClsYOpdZpgm7zJg==",
        "qeAuthData": {
          "parsedDataSize": 32,
          "data": "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
        },
        "pckCertificateChainData": {
          "certificateDataType": 5,
          "size": 3678,
          "pckCertChain": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4RENDQkphZ0F3SUJBZ0lVRzBMcFhKNGFNN0J6WTZnL2Z1dUsydkUrbmN3d0NnWUlLb1pJemowRUF3SXcKY0RFaU1DQUdBMVVFQXd3WlNXNTBaV3dnVTBkWUlGQkRTeUJRYkdGMFptOXliU0JEUVRFYU1CZ0dBMVVFQ2d3UgpTVzUwWld3Z1EyOXljRzl5WVhScGIyNHhGREFTQmdOVkJBY01DMU5oYm5SaElFTnNZWEpoTVFzd0NRWURWUVFJCkRBSkRRVEVMTUFrR0ExVUVCaE1DVlZNd0hoY05NalV4TWpBNU1UUTBNRE00V2hjTk16SXhNakE1TVRRME1ETTQKV2pCd01TSXdJQVlEVlFRRERCbEpiblJsYkNCVFIxZ2dVRU5MSUVObGNuUnBabWxqWVhSbE1Sb3dHQVlEVlFRSwpEQkZKYm5SbGJDQkRiM0p3YjNKaGRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WCkJBZ01Ba05CTVFzd0NRWURWUVFHRXdKVlV6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIRHcKL3lEa3BnaU5RTm45R0w3eDc4VzY3VG5LNVZJd05YckJVNmVUVjVEK3I5Mmk2SVZmZVlOSDNOeHREQmNFQkhkUgp2WVFvUGRSTGRxNjM2RTRHNlQyamdnTU1NSUlEQ0RBZkJnTlZIU01FR0RBV2dCU1ZiMTNOdlJ2aDZVQkp5ZFQwCk04NEJWd3ZlVkRCckJnTlZIUjhFWkRCaU1HQ2dYcUJjaGxwb2RIUndjem92TDJGd2FTNTBjblZ6ZEdWa2MyVnkKZG1salpYTXVhVzUwWld3dVkyOXRMM05uZUM5alpYSjBhV1pwWTJGMGFXOXVMM1kwTDNCamEyTnliRDlqWVQxdwpiR0YwWm05eWJTWmxibU52WkdsdVp6MWtaWEl3SFFZRFZSME9CQllFRk0zL1NxZnVRdTJOWGJWYWJ5aytUS1lLCnI2RDZNQTRHQTFVZER3RUIvd1FFQXdJR3dEQU1CZ05WSFJNQkFmOEVBakFBTUlJQ09RWUpLb1pJaHZoTkFRMEIKQklJQ0tqQ0NBaVl3SGdZS0tvWklodmhOQVEwQkFRUVFtT2l2Smh5QnFQbS9NSVBLM24vcjVEQ0NBV01HQ2lxRwpTSWI0VFFFTkFRSXdnZ0ZUTUJBR0N5cUdTSWI0VFFFTkFRSUJBZ0VETUJBR0N5cUdTSWI0VFFFTkFRSUNBZ0VECk1CQUdDeXFHU0liNFRRRU5BUUlEQWdFQ01CQUdDeXFHU0liNFRRRU5BUUlFQWdFQ01CQUdDeXFHU0liNFRRRU4KQVFJRkFnRUVNQkFHQ3lxR1NJYjRUUUVOQVFJR0FnRUJNQkFHQ3lxR1NJYjRUUUVOQVFJSEFnRUFNQkFHQ3lxRwpTSWI0VFFFTkFRSUlBZ0VGTUJBR0N5cUdTSWI0VFFFTkFRSUpBZ0VBTUJBR0N5cUdTSWI0VFFFTkFRSUtBZ0VBCk1CQUdDeXFHU0liNFRRRU5BUUlMQWdFQU1CQUdDeXFHU0liNFRRRU5BUUlNQWdFQU1CQUdDeXFHU0liNFRRRU4KQVFJTkFnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJT0FnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJUEFnRUFNQkFHQ3lxRwpTSWI0VFFFTkFRSVFBZ0VBTUJBR0N5cUdTSWI0VFFFTkFRSVJBZ0VOTUI4R0N5cUdTSWI0VFFFTkFRSVNCQkFECkF3SUNCQUVBQlFBQUFBQUFBQUFBTUJBR0NpcUdTSWI0VFFFTkFRTUVBZ0FBTUJRR0NpcUdTSWI0VFFFTkFRUUUKQnBEQWJ3QUFBREFQQmdvcWhraUcrRTBCRFFFRkNnRUJNQjRHQ2lxR1NJYjRUUUVOQVFZRUVPa0NFSEFxTE1XdApsMlR5bmR5UDNvd3dSQVlLS29aSWh2aE5BUTBCQnpBMk1CQUdDeXFHU0liNFRRRU5BUWNCQVFIL01CQUdDeXFHClNJYjRUUUVOQVFjQ0FRSC9NQkFHQ3lxR1NJYjRUUUVOQVFjREFRSC9NQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUMKSVFEenlZUFZ5RS9RYU1QSk5VajR1Sk1tVlk2SGZkNnBoYzdQZUZOL3A0MDArUUlnVVNhMW5BcEcxdUFsZVNZVwp1Q1Rya2pMemRJeTVFcUFFLytXRmVNd05EeHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNsakNDQWoyZ0F3SUJBZ0lWQUpWdlhjMjlHK0hwUUVuSjFQUXp6Z0ZYQzk1VU1Bb0dDQ3FHU000OUJBTUMKTUdneEdqQVlCZ05WQkFNTUVVbHVkR1ZzSUZOSFdDQlNiMjkwSUVOQk1Sb3dHQVlEVlFRS0RCRkpiblJsYkNCRApiM0p3YjNKaGRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUXN3CkNRWURWUVFHRXdKVlV6QWVGdzB4T0RBMU1qRXhNRFV3TVRCYUZ3MHpNekExTWpFeE1EVXdNVEJhTUhBeElqQWcKQmdOVkJBTU1HVWx1ZEdWc0lGTkhXQ0JRUTBzZ1VHeGhkR1p2Y20wZ1EwRXhHakFZQmdOVkJBb01FVWx1ZEdWcwpJRU52Y25CdmNtRjBhVzl1TVJRd0VnWURWUVFIREF0VFlXNTBZU0JEYkdGeVlURUxNQWtHQTFVRUNBd0NRMEV4CkN6QUpCZ05WQkFZVEFsVlRNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVOU0IvN3QyMWxYU08KMkN1enB4dzc0ZUpCNzJFeURHZ1c1clhDdHgydFZUTHE2aEtrNnorVWlSWkNucVI3cHNPdmdxRmVTeGxtVGxKbAplVG1pMldZejNxT0J1ekNCdURBZkJnTlZIU01FR0RBV2dCUWlaUXpXV3AwMGlmT0R0SlZTdjFBYk9TY0dyREJTCkJnTlZIUjhFU3pCSk1FZWdSYUJEaGtGb2RIUndjem92TDJObGNuUnBabWxqWVhSbGN5NTBjblZ6ZEdWa2MyVnkKZG1salpYTXVhVzUwWld3dVkyOXRMMGx1ZEdWc1UwZFlVbTl2ZEVOQkxtUmxjakFkQmdOVkhRNEVGZ1FVbFc5ZAp6YjBiNGVsQVNjblU5RFBPQVZjTDNsUXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCCkFmOENBUUF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnWHNWa2kwdytpNlZZR1czVUYvMjJ1YVhlMFlKRGoxVWUKbkErVGpEMWFpNWNDSUNZYjFTQW1ENXhrZlRWcHZvNFVveWlTWXhyRFdMbVVSNENJOU5LeWZQTisKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ2p6Q0NBalNnQXdJQkFnSVVJbVVNMWxxZE5JbnpnN1NWVXI5UUd6a25CcXd3Q2dZSUtvWkl6ajBFQXdJdwphREVhTUJnR0ExVUVBd3dSU1c1MFpXd2dVMGRZSUZKdmIzUWdRMEV4R2pBWUJnTlZCQW9NRVVsdWRHVnNJRU52CmNuQnZjbUYwYVc5dU1SUXdFZ1lEVlFRSERBdFRZVzUwWVNCRGJHRnlZVEVMTUFrR0ExVUVDQXdDUTBFeEN6QUoKQmdOVkJBWVRBbFZUTUI0WERURTRNRFV5TVRFd05EVXhNRm9YRFRRNU1USXpNVEl6TlRrMU9Wb3dhREVhTUJnRwpBMVVFQXd3UlNXNTBaV3dnVTBkWUlGSnZiM1FnUTBFeEdqQVlCZ05WQkFvTUVVbHVkR1ZzSUVOdmNuQnZjbUYwCmFXOXVNUlF3RWdZRFZRUUhEQXRUWVc1MFlTQkRiR0Z5WVRFTE1Ba0dBMVVFQ0F3Q1EwRXhDekFKQmdOVkJBWVQKQWxWVE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUM2bkV3TURJWVpPai9pUFdzQ3phRUtpNwoxT2lPU0xSRmhXR2pibkJWSmZWbmtZNHUzSWprRFlZTDBNeE80bXFzeVlqbEJhbFRWWXhGUDJzSkJLNXpsS09CCnV6Q0J1REFmQmdOVkhTTUVHREFXZ0JRaVpReldXcDAwaWZPRHRKVlN2MUFiT1NjR3JEQlNCZ05WSFI4RVN6QkoKTUVlZ1JhQkRoa0ZvZEhSd2N6b3ZMMk5sY25ScFptbGpZWFJsY3k1MGNuVnpkR1ZrYzJWeWRtbGpaWE11YVc1MApaV3d1WTI5dEwwbHVkR1ZzVTBkWVVtOXZkRU5CTG1SbGNqQWRCZ05WSFE0RUZnUVVJbVVNMWxxZE5JbnpnN1NWClVyOVFHemtuQnF3d0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0NnWUkKS29aSXpqMEVBd0lEU1FBd1JnSWhBT1cvNVFrUitTOUNpU0RjTm9vd0x1UFJMc1dHZi9ZaTdHU1g5NEJnd1R3ZwpBaUVBNEowbHJIb01zK1hvNW8vc1g2TzlRV3hIUkF2WlVHT2RSUTdjdnFSWGFxST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoA"
        }
      }
    }
  },
  "extraBytes": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
}
`
