# Copyright 2024 Edgeless Systems GmbH
# SPDX-License-Identifier: AGPL-3.0-only

{ fetchurl
, stdenvNoCC
, igvmmeasure
}:
let
  # Currently, those are files extracted from the CoCo AKS node image (AKSCBLMariner-V2katagen2).
  # In the future, those will be generated by us.
  rootfs = fetchurl {
    url = "https://cdn.confidential.cloud/contrast/node-components/1714998420/kata-containers.img";
    hash = "sha256-VzJ2c8rtBAt6PzIoz4MSVYfYadXSL8M9hmnSuaMgbNg=";
  };
  igvm = fetchurl {
    url = "https://cdn.confidential.cloud/contrast/node-components/1714998420/kata-containers-igvm.img";
    hash = "sha256-+JbqZnrxgulpfgqAgDnlpBlfa87L92gIVUFefsgnINs=";
  };
  cloud-hypervisor-bin = fetchurl {
    url = "https://cdn.confidential.cloud/contrast/node-components/1714998420/cloud-hypervisor-cvm";
    hash = "sha256-coTHzd5/QLjlPQfrp9d2TJTIXKNuANTN7aNmpa8PRXo=";
  };
  containerd-shim-contrast-cc-v2 = fetchurl {
    url = "https://cdn.confidential.cloud/contrast/node-components/1714998420/containerd-shim-kata-cc-v2";
    hash = "sha256-yhk3ZearqQVz1X1p67OFPCSHbF0P66E7KknpO/JGzZg=";
  };
in
stdenvNoCC.mkDerivation {
  name = "runtime-class-files";
  version = "1714998420";

  dontUnpack = true;

  buildInputs = [ igvmmeasure ];

  buildPhase = ''
    mkdir -p $out
    igvmmeasure -b ${igvm} | dd conv=lcase > $out/launch-digest.hex
    echo -n "contrast-cc-" > $out/runtime-handler
    cat $out/launch-digest.hex | head -c 32 >> $out/runtime-handler
  '';

  passthru = {
    inherit rootfs igvm cloud-hypervisor-bin containerd-shim-contrast-cc-v2;
  };
}
