changelog:
  categories:
    - title: 🛠 Breaking changes
      labels:
        - breaking change
    - title: 🎁 New features
      labels:
        - feature
    - title: 🐛 Bug fixes
      labels:
        - bug fix
    - title: 🔧 Other changes
      labels:
        - changelog
    - title: 📖 Documentation
      labels:
        - documentation
