version: "2"
run:
  build-tags:
    - e2e
    - contrast_unstable_api
  modules-download-mode: readonly
output:
  formats:
    tab:
      path: stderr
linters:
  enable:
    # keep-sorted start
    - bodyclose
    - contextcheck
    - copyloopvar
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - godot
    - intrange
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - sloglint
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    # keep-sorted end
  settings:
    testifylint:
      disable:
        - require-error
    revive:
      rules:
        - name: "package-comments"
          disabled: true
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - std-error-handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 20
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: strict
