run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - e2e

output:
  formats:
    - format: colored-tab
      path: stderr
  sort-results: true

linters-settings:
  testifylint:
    disable:
      - require-error

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - errname
    - exportloopref
    - godot
    - gofumpt
    - misspell
    - noctx
    - revive
    - tenv
    - unconvert
    - unparam
    - contextcheck
    - errchkjson
    - errorlint
    - gocheckcompilerdirectives
    - nilerr
    - predeclared
    - sloglint
    - testifylint
    - usestdlibvars

issues:
  max-issues-per-linter: 0
  max-same-issues: 20
  include:
    - EXC0012
    - EXC0014
