run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - e2e

output:
  formats:
    - format: colored-tab
      path: stderr
  sort-results: true

linters-settings:
  testifylint:
    disable:
      - require-error

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    # keep-sorted start
    - bodyclose
    - contextcheck
    - copyloopvar
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - godot
    - gofumpt
    - intrange
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - sloglint
    - tenv
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    # keep-sorted end

issues:
  max-issues-per-linter: 0
  max-same-issues: 20
  include:
    - EXC0012
    - EXC0014
