name: Post to teams
description: Post a message to the teams channel

inputs:
  webhook:
    description: "The webhook to send the message to."
    required: true
  title:
    description: "The title of the notification."
    required: true
  message:
    description: "The message to be sent. Note that you may not use quotes or escaped quotes in your message."
    required: true
  additionalFields:
    description: "Additional fields to add to the Teams message (JSON formatted)"
    default: "[]"
  additionalActions:
    description: "Additional actions (buttons) to add to the Teams message (JSON formatted)"
    default: "[]"
runs:
  using: "composite"
  steps:
    - name: Post to teams
      shell: bash
      env:
        INPUTS_TITLE: ${{inputs.title}}
        INPUTS_MESSAGE: ${{inputs.message}}
        INPUTS_ADDITIONALFIELDS: ${{inputs.additionalFields}}
        INPUTS_ADDITIONALACTIONS: ${{inputs.additionalActions}}
        INPUTS_WEBHOOK: ${{inputs.webhook}}
      run: |
        cp .github/actions/post_to_teams/teams_card_template.json template.json

        # add the title
        yq -oj -iP ".attachments[0].content.body[0].columns[1].items[0].text = \"${INPUTS_TITLE}\"" ./template.json

        # add the message
        yq -oj -iP ".attachments[0].content.body[1].text = \"${INPUTS_MESSAGE}\"" ./template.json

        # add the run url to the clickable button
        yq -oj -iP ".attachments[0].content.actions[0].url = \"${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}\"" ./template.json

        # update the fact set
        yq -oj -iP ".attachments[0].content.body[0].columns[1].items[1].facts[0].value = \"${{github.run_id}}\"" ./template.json
        yq -oj -iP ".attachments[0].content.body[0].columns[1].items[1].facts[1].value = \"${GITHUB_REF_NAME}\"" ./template.json

        # add additional fields
        yq -oj -iP ".attachments[0].content.body[0].columns[1].items[1].facts += ${INPUTS_ADDITIONALFIELDS}" ./template.json

        # add additional buttons
        yq -oj -iP ".attachments[0].content.actions += ${INPUTS_ADDITIONALACTIONS}" ./template.json

        payload="$(cat ./template.json)"
        curl \
          -H "Content-Type: application/json" \
          -d "$payload" \
          "${INPUTS_WEBHOOK}"
