// Copyright 2025 Edgeless Systems GmbH
// SPDX-License-Identifier: BUSL-1.1

package validator

import (
	"testing"

	"github.com/google/go-tdx-guest/abi"
	"github.com/google/go-tdx-guest/proto/tdx"
	"github.com/stretchr/testify/assert"
	"google.golang.org/protobuf/encoding/protojson"
)

func TestGetDigestTDX(t *testing.T) {
	for name, tc := range map[string]struct {
		mrConfigID []byte
		err        error
	}{
		"success": {mrConfigID: newSlice(48)},
		"error":   {err: assert.AnError},
	} {
		t.Run(name, func(t *testing.T) {
			assert := assert.New(t)
			qp := &stubTDXQuoteProvider{
				mrConfigID: tc.mrConfigID,
				err:        tc.err,
			}
			g := &tdxDigestGetter{qp}
			digest, err := g.GetDigest()
			assert.ErrorIs(err, tc.err)
			assert.Equal(tc.mrConfigID, digest)
		})
	}
}

type stubTDXQuoteProvider struct {
	mrConfigID []byte
	err        error
}

func (s *stubTDXQuoteProvider) IsSupported() error {
	return nil
}

func (s *stubTDXQuoteProvider) GetRawQuote(reportData [64]byte) ([]uint8, error) {
	if s.err != nil {
		return nil, s.err
	}
	// This fakes a TDX quote by loading a quote obtained somewhere else and replacing MRCONFIGID.
	quote := tdx.QuoteV4{}
	if err := protojson.Unmarshal([]byte(cannedTDXQuoteJSON), &quote); err != nil {
		return nil, err
	}
	quote.TdQuoteBody.MrConfigId = s.mrConfigID
	quote.TdQuoteBody.ReportData = reportData[:]

	return abi.QuoteToAbiBytes(&quote)
}

const cannedTDXQuoteJSON = `
{
  "header": {
    "version": 4,
    "attestationKeyType": 2,
    "teeType": 129,
    "qeSvn": "AAA=",
    "pceSvn": "AAA=",
    "qeVendorId": "k5pyM/ecTKmUCg2zlX8GBw==",
    "userData": "I4UkNxULgFFFZaZyUY/ANwAAAAA="
  },
  "tdQuoteBody": {
    "teeTcbSvn": "BgEDAAAAAAAAAAAAAAAAAA==",
    "mrSeam": "WzjjOmSHlYtyw8Eqk46qXj/UUQxRruq1jH1ezuQdfENkidbI5PkvFgt8rTQgewDB",
    "mrSignerSeam": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "seamAttributes": "AAAAAAAAAAA=",
    "tdAttributes": "AAAAEAAAAAA=",
    "xfam": "5wIGAAAAAAA=",
    "mrTd": "dvxVr0t6XHjzd12v8fliOGD5USjG2kglbegFCQsmRILdw0+fIlpjEt+KQgljVbJJ",
    "mrConfigId": "WhW/bsTpPcw6UGSCI0E3UvzvkBJFKL3CXpxzb+qogMYAAAAAAAAAAAAAAAAAAAAA",
    "mrOwner": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "mrOwnerConfig": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "rtmrs": [
      "PQrSJoSoxoYc0Tb0LGuO2wLyc/GEU8Y04saj0zIGApmYXnjRpBWZPeI7JkmfmU95",
      "H8k12/pbBfHOssF0DOOB8wk98B2HD2KYZJCZ4qU9l1lVxMGdk9ElrL7ETIw/ib3j",
      "++TV0SIw35nT7OvOJKKzDYGavTFfzGtqiOZrLChLZflisMQjBgs1Z99oaZNLl8ZM",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    ],
    "reportData": "HUyHUurSkNffreJOMwKE3HGj9p7uyu6gpfuTLo+BmGid0OuO4GqbXmcx6h/1BEQfQ9pzoygr7XmhwyJD7nTwbg=="
  },
  "signedDataSize": 4300,
  "signedData": {
    "signature": "appk+7Rj+KaNtrs4J0JZEwi6Uc6BWa0zkQ7SNrt8FfDIgVUdGnJqLhRVyk5VzCOhqtBIs2DZXqZWSQrnGYX6hA==",
    "ecdsaAttestationKey": "cXZeposNTjUKEdkCh4fPALkhEwyp61UJ2WXXKsLeR2wAnDYK3665MkpSIgS4wgGFmXJTCwGzezThl6DU29GJUA==",
    "certificationData": {
      "certificateDataType": 6,
      "size": 4166,
      "qeReportCertificationData": {
        "qeReport": {
          "cpuSvn": "AwMZGwT/AAYAAAAAAAAAAA==",
          "reserved1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
          "attributes": "FQAAAAAAAADnAAAAAAAAAA==",
          "mrEnclave": "5aOntdgwwpU7mFNMbFmjo0/cNOkz9/WJjwqFzwiEa8o=",
          "reserved2": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
          "mrSigner": "3J4qfG+UjxdHTjSn/EPtAw98FWPxur3fY0DILg5UqMU=",
          "reserved3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "isvProdId": 2,
          "isvSvn": 6,
          "reserved4": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "reportData": "pSdgYInF5v5moc9tEZkrgETgvNyk+73LGIk2Qaze8YkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        },
        "qeReportSignature": "4DWDyIrja4U6iPSZWcvDOv5+ICFMXDjE257XT6vi6MNrej29Gfs8HaL5vt8AyBQSyBTVNuoHCsPed98Uh9dn2Q==",
        "qeAuthData": {
          "parsedDataSize": 32,
          "data": "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
        },
        "pckCertificateChainData": {
          "certificateDataType": 5,
          "size": 3678,
          "pckCertChain": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4VENDQkphZ0F3SUJBZ0lVQlBxckw0V3lBNFpWbE9KTUtzNFZ6ZEpCL0hRd0NnWUlLb1pJemowRUF3SXcKY0RFaU1DQUdBMVVFQXd3WlNXNTBaV3dnVTBkWUlGQkRTeUJRYkdGMFptOXliU0JEUVRFYU1CZ0dBMVVFQ2d3UgpTVzUwWld3Z1EyOXljRzl5WVhScGIyNHhGREFTQmdOVkJBY01DMU5oYm5SaElFTnNZWEpoTVFzd0NRWURWUVFJCkRBSkRRVEVMTUFrR0ExVUVCaE1DVlZNd0hoY05NalV3TmpFNE1UUXpOalV5V2hjTk16SXdOakU0TVRRek5qVXkKV2pCd01TSXdJQVlEVlFRRERCbEpiblJsYkNCVFIxZ2dVRU5MSUVObGNuUnBabWxqWVhSbE1Sb3dHQVlEVlFRSwpEQkZKYm5SbGJDQkRiM0p3YjNKaGRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WCkJBZ01Ba05CTVFzd0NRWURWUVFHRXdKVlV6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFbE0KOFc0ZjVDQ2lzSUFaZnZUL3M5RXRWZ1FnSzRTMVhMbTlreGJDU1lhcms3dzVjZTdkSFRyY3B3Q0hlL21FdjY3VQpidXlOd0ZCc2MwZW4xcUd4YUd5amdnTU1NSUlEQ0RBZkJnTlZIU01FR0RBV2dCU1ZiMTNOdlJ2aDZVQkp5ZFQwCk04NEJWd3ZlVkRCckJnTlZIUjhFWkRCaU1HQ2dYcUJjaGxwb2RIUndjem92TDJGd2FTNTBjblZ6ZEdWa2MyVnkKZG1salpYTXVhVzUwWld3dVkyOXRMM05uZUM5alpYSjBhV1pwWTJGMGFXOXVMM1kwTDNCamEyTnliRDlqWVQxdwpiR0YwWm05eWJTWmxibU52WkdsdVp6MWtaWEl3SFFZRFZSME9CQllFRlBkZDYvQlV2cDJXSGVyMUl2YzAyRnlJCmJKM2tNQTRHQTFVZER3RUIvd1FFQXdJR3dEQU1CZ05WSFJNQkFmOEVBakFBTUlJQ09RWUpLb1pJaHZoTkFRMEIKQklJQ0tqQ0NBaVl3SGdZS0tvWklodmhOQVEwQkFRUVE0MXJha1RFaGVuNzVjYVNvbUdvYWtEQ0NBV01HQ2lxRwpTSWI0VFFFTkFRSXdnZ0ZUTUJBR0N5cUdTSWI0VFFFTkFRSUJBZ0VETUJBR0N5cUdTSWI0VFFFTkFRSUNBZ0VECk1CQUdDeXFHU0liNFRRRU5BUUlEQWdFQ01CQUdDeXFHU0liNFRRRU5BUUlFQWdFQ01CQUdDeXFHU0liNFRRRU4KQVFJRkFnRUVNQkFHQ3lxR1NJYjRUUUVOQVFJR0FnRUJNQkFHQ3lxR1NJYjRUUUVOQVFJSEFnRUFNQkFHQ3lxRwpTSWI0VFFFTkFRSUlBZ0VGTUJBR0N5cUdTSWI0VFFFTkFRSUpBZ0VBTUJBR0N5cUdTSWI0VFFFTkFRSUtBZ0VBCk1CQUdDeXFHU0liNFRRRU5BUUlMQWdFQU1CQUdDeXFHU0liNFRRRU5BUUlNQWdFQU1CQUdDeXFHU0liNFRRRU4KQVFJTkFnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJT0FnRUFNQkFHQ3lxR1NJYjRUUUVOQVFJUEFnRUFNQkFHQ3lxRwpTSWI0VFFFTkFRSVFBZ0VBTUJBR0N5cUdTSWI0VFFFTkFRSVJBZ0VMTUI4R0N5cUdTSWI0VFFFTkFRSVNCQkFECkF3SUNCQUVBQlFBQUFBQUFBQUFBTUJBR0NpcUdTSWI0VFFFTkFRTUVBZ0FBTUJRR0NpcUdTSWI0VFFFTkFRUUUKQnJEQWJ3QUFBREFQQmdvcWhraUcrRTBCRFFFRkNnRUJNQjRHQ2lxR1NJYjRUUUVOQVFZRUVGa0NqZVJuSmI0UgpudWlhRUFBckdSd3dSQVlLS29aSWh2aE5BUTBCQnpBMk1CQUdDeXFHU0liNFRRRU5BUWNCQVFIL01CQUdDeXFHClNJYjRUUUVOQVFjQ0FRSC9NQkFHQ3lxR1NJYjRUUUVOQVFjREFRSC9NQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUMKSVFDdDFZNU41SkM2Qm1NQjByblRNOG9YRmRicHBvMm1SQmFUUXN2L2ZYUGdaUUloQUt4VHpiaERrc3pVZzBwbQpSckVTTXNTbEszNGlKYko2VlNHemdjdVJ0Sm8zCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNsakNDQWoyZ0F3SUJBZ0lWQUpWdlhjMjlHK0hwUUVuSjFQUXp6Z0ZYQzk1VU1Bb0dDQ3FHU000OUJBTUMKTUdneEdqQVlCZ05WQkFNTUVVbHVkR1ZzSUZOSFdDQlNiMjkwSUVOQk1Sb3dHQVlEVlFRS0RCRkpiblJsYkNCRApiM0p3YjNKaGRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUXN3CkNRWURWUVFHRXdKVlV6QWVGdzB4T0RBMU1qRXhNRFV3TVRCYUZ3MHpNekExTWpFeE1EVXdNVEJhTUhBeElqQWcKQmdOVkJBTU1HVWx1ZEdWc0lGTkhXQ0JRUTBzZ1VHeGhkR1p2Y20wZ1EwRXhHakFZQmdOVkJBb01FVWx1ZEdWcwpJRU52Y25CdmNtRjBhVzl1TVJRd0VnWURWUVFIREF0VFlXNTBZU0JEYkdGeVlURUxNQWtHQTFVRUNBd0NRMEV4CkN6QUpCZ05WQkFZVEFsVlRNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVOU0IvN3QyMWxYU08KMkN1enB4dzc0ZUpCNzJFeURHZ1c1clhDdHgydFZUTHE2aEtrNnorVWlSWkNucVI3cHNPdmdxRmVTeGxtVGxKbAplVG1pMldZejNxT0J1ekNCdURBZkJnTlZIU01FR0RBV2dCUWlaUXpXV3AwMGlmT0R0SlZTdjFBYk9TY0dyREJTCkJnTlZIUjhFU3pCSk1FZWdSYUJEaGtGb2RIUndjem92TDJObGNuUnBabWxqWVhSbGN5NTBjblZ6ZEdWa2MyVnkKZG1salpYTXVhVzUwWld3dVkyOXRMMGx1ZEdWc1UwZFlVbTl2ZEVOQkxtUmxjakFkQmdOVkhRNEVGZ1FVbFc5ZAp6YjBiNGVsQVNjblU5RFBPQVZjTDNsUXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCCkFmOENBUUF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnWHNWa2kwdytpNlZZR1czVUYvMjJ1YVhlMFlKRGoxVWUKbkErVGpEMWFpNWNDSUNZYjFTQW1ENXhrZlRWcHZvNFVveWlTWXhyRFdMbVVSNENJOU5LeWZQTisKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ2p6Q0NBalNnQXdJQkFnSVVJbVVNMWxxZE5JbnpnN1NWVXI5UUd6a25CcXd3Q2dZSUtvWkl6ajBFQXdJdwphREVhTUJnR0ExVUVBd3dSU1c1MFpXd2dVMGRZSUZKdmIzUWdRMEV4R2pBWUJnTlZCQW9NRVVsdWRHVnNJRU52CmNuQnZjbUYwYVc5dU1SUXdFZ1lEVlFRSERBdFRZVzUwWVNCRGJHRnlZVEVMTUFrR0ExVUVDQXdDUTBFeEN6QUoKQmdOVkJBWVRBbFZUTUI0WERURTRNRFV5TVRFd05EVXhNRm9YRFRRNU1USXpNVEl6TlRrMU9Wb3dhREVhTUJnRwpBMVVFQXd3UlNXNTBaV3dnVTBkWUlGSnZiM1FnUTBFeEdqQVlCZ05WQkFvTUVVbHVkR1ZzSUVOdmNuQnZjbUYwCmFXOXVNUlF3RWdZRFZRUUhEQXRUWVc1MFlTQkRiR0Z5WVRFTE1Ba0dBMVVFQ0F3Q1EwRXhDekFKQmdOVkJBWVQKQWxWVE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUM2bkV3TURJWVpPai9pUFdzQ3phRUtpNwoxT2lPU0xSRmhXR2pibkJWSmZWbmtZNHUzSWprRFlZTDBNeE80bXFzeVlqbEJhbFRWWXhGUDJzSkJLNXpsS09CCnV6Q0J1REFmQmdOVkhTTUVHREFXZ0JRaVpReldXcDAwaWZPRHRKVlN2MUFiT1NjR3JEQlNCZ05WSFI4RVN6QkoKTUVlZ1JhQkRoa0ZvZEhSd2N6b3ZMMk5sY25ScFptbGpZWFJsY3k1MGNuVnpkR1ZrYzJWeWRtbGpaWE11YVc1MApaV3d1WTI5dEwwbHVkR1ZzVTBkWVVtOXZkRU5CTG1SbGNqQWRCZ05WSFE0RUZnUVVJbVVNMWxxZE5JbnpnN1NWClVyOVFHemtuQnF3d0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFFd0NnWUkKS29aSXpqMEVBd0lEU1FBd1JnSWhBT1cvNVFrUitTOUNpU0RjTm9vd0x1UFJMc1dHZi9ZaTdHU1g5NEJnd1R3ZwpBaUVBNEowbHJIb01zK1hvNW8vc1g2TzlRV3hIUkF2WlVHT2RSUTdjdnFSWGFxST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoA"
        }
      }
    }
  },
  "extraBytes": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
}
`
