// source: https://github.com/kata-containers/kata-containers/blob/997a1f35ab68ad8cc2b24e8e20ea63f7de82acf9/src/libs/protocols/protos/confidential_data_hub.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: securemount.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecureMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeType    string                 `protobuf:"bytes,1,opt,name=volume_type,json=volumeType,proto3" json:"volume_type,omitempty"`
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Flags         []string               `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	MountPoint    string                 `protobuf:"bytes,4,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureMountRequest) Reset() {
	*x = SecureMountRequest{}
	mi := &file_securemount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureMountRequest) ProtoMessage() {}

func (x *SecureMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securemount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureMountRequest.ProtoReflect.Descriptor instead.
func (*SecureMountRequest) Descriptor() ([]byte, []int) {
	return file_securemount_proto_rawDescGZIP(), []int{0}
}

func (x *SecureMountRequest) GetVolumeType() string {
	if x != nil {
		return x.VolumeType
	}
	return ""
}

func (x *SecureMountRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SecureMountRequest) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *SecureMountRequest) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

type SecureMountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPath     string                 `protobuf:"bytes,1,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureMountResponse) Reset() {
	*x = SecureMountResponse{}
	mi := &file_securemount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureMountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureMountResponse) ProtoMessage() {}

func (x *SecureMountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securemount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureMountResponse.ProtoReflect.Descriptor instead.
func (*SecureMountResponse) Descriptor() ([]byte, []int) {
	return file_securemount_proto_rawDescGZIP(), []int{1}
}

func (x *SecureMountResponse) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

var File_securemount_proto protoreflect.FileDescriptor

const file_securemount_proto_rawDesc = "" +
	"\n" +
	"\x11securemount.proto\x12\x03api\"\xe8\x01\n" +
	"\x12SecureMountRequest\x12\x1f\n" +
	"\vvolume_type\x18\x01 \x01(\tR\n" +
	"volumeType\x12>\n" +
	"\aoptions\x18\x02 \x03(\v2$.api.SecureMountRequest.OptionsEntryR\aoptions\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\tR\x05flags\x12\x1f\n" +
	"\vmount_point\x18\x04 \x01(\tR\n" +
	"mountPoint\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x13SecureMountResponse\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x01 \x01(\tR\tmountPath2X\n" +
	"\x12SecureMountService\x12B\n" +
	"\vSecureMount\x12\x17.api.SecureMountRequest\x1a\x18.api.SecureMountResponse\"\x00B:Z8github.com/edgelesssys/contrast/securemount/internal/apib\x06proto3"

var (
	file_securemount_proto_rawDescOnce sync.Once
	file_securemount_proto_rawDescData []byte
)

func file_securemount_proto_rawDescGZIP() []byte {
	file_securemount_proto_rawDescOnce.Do(func() {
		file_securemount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_securemount_proto_rawDesc), len(file_securemount_proto_rawDesc)))
	})
	return file_securemount_proto_rawDescData
}

var file_securemount_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_securemount_proto_goTypes = []any{
	(*SecureMountRequest)(nil),  // 0: api.SecureMountRequest
	(*SecureMountResponse)(nil), // 1: api.SecureMountResponse
	nil,                         // 2: api.SecureMountRequest.OptionsEntry
}
var file_securemount_proto_depIdxs = []int32{
	2, // 0: api.SecureMountRequest.options:type_name -> api.SecureMountRequest.OptionsEntry
	0, // 1: api.SecureMountService.SecureMount:input_type -> api.SecureMountRequest
	1, // 2: api.SecureMountService.SecureMount:output_type -> api.SecureMountResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_securemount_proto_init() }
func file_securemount_proto_init() {
	if File_securemount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_securemount_proto_rawDesc), len(file_securemount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_securemount_proto_goTypes,
		DependencyIndexes: file_securemount_proto_depIdxs,
		MessageInfos:      file_securemount_proto_msgTypes,
	}.Build()
	File_securemount_proto = out.File
	file_securemount_proto_goTypes = nil
	file_securemount_proto_depIdxs = nil
}
