name: setup nix
description: Setup nix and cachix

inputs:
  githubToken:
    description: "Token to authenticate with GitHub"
    required: true
  cachixToken:
    description: "Token to authenticate with cachix"
    required: true

runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      with:
        github_access_token: ${{ inputs.githubToken }}
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: edgelesssys
        authToken: ${{ inputs.cachixToken }}
    - name: use btrfs for nix builds
      shell: bash
      run: |
        sudo mkdir /nixbld
        truncate -s 3G btrfs.img
        sudo mkfs.btrfs -f btrfs.img
        sudo mount btrfs.img /nixbld
        sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
        echo -e "[Service]\nEnvironment=TMPDIR=/nixbld" | sudo tee /etc/systemd/system/nix-daemon.service.d/btrfs.conf
        sudo systemctl daemon-reload
        sudo systemctl restart nix-daemon
