name: setup nix
description: Setup nix and cachix

inputs:
  githubToken:
    description: "Token to authenticate with GitHub"
    required: true
  cachixToken:
    description: "Token to authenticate with cachix"
    required: true

runs:
  using: "composite"
  steps:
    - name: Allow unrestricted user namespaces
      if: runner.os == 'Linux'
      # Ubuntu 24.04 ships strict apparmor defaults, so we have to disable them to be able to call
      # unshare in the Nix sansbox without beeing root.
      shell: bash
      run: |
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_userns=0
    - name: use btrfs for nix builds
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "Setting up btrfs /nix volume..."
        sudo mkdir -p /nix
        sudo truncate -s 50G /mnt/btrfs.img
        sudo mkfs.btrfs -f /mnt/btrfs.img
        sudo mount /mnt/btrfs.img /nix
        sudo mkdir -p /nix/bld
        sudo findmnt
        sudo df -h
    - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
      with:
        github_access_token: ${{ inputs.githubToken }}
        extra_nix_config: ${{ runner.os == 'Linux' && 'build-dir = /nix/bld' || '' }}
    - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: edgelesssys
        authToken: ${{ inputs.cachixToken }}
