name: setup nix
description: Setup nix and cachix

inputs:
  githubToken:
    description: "Token to authenticate with GitHub"
    required: true
  cachixToken:
    description: "Token to authenticate with cachix"
    required: true

runs:
  using: "composite"
  steps:
    - name: Allow unrestricted user namespaces
      # Ubuntu 24.04 ships strict apparmor defaults, so we have to disable them to be able to call
      # unshare in the Nix sansbox without beeing root.
      shell: bash
      run: |
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_userns=0
    - name: use btrfs for nix builds
      shell: bash
      run: |
        echo "Setting up btrfs /nix volume..."
        sudo mkdir -p /nix
        sudo truncate -s 50G /mnt/btrfs.img
        sudo mkfs.btrfs -f /mnt/btrfs.img
        sudo mount /mnt/btrfs.img /nix
        sudo mkdir -p /nix/bld
        sudo findmnt
        sudo df -h
    - uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      with:
        github_access_token: ${{ inputs.githubToken }}
        extra_nix_config: "build-dir = /nix/bld"
    - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: edgelesssys
        authToken: ${{ inputs.cachixToken }}
