name: setup nix
description: Setup nix and cachix

inputs:
  githubToken:
    description: "Token to authenticate with GitHub"
    required: true
  cachixToken:
    description: "Token to authenticate with cachix"
    required: true

runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@9f70348d77d0422624097c4b7a75563948901306 # v29
      with:
        github_access_token: ${{ inputs.githubToken }}
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: edgelesssys
        authToken: ${{ inputs.cachixToken }}
    - name: use btrfs for nix builds
      shell: bash
      run: |
        sudo df -h

        echo "Removing unwanted software... "
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker system prune --all --force
        sudo df -h

        echo "Setting up btrfs nix builder volume..."
        sudo mkdir -p /mnt/nixbld
        sudo truncate -s 20G /mnt/btrfs.img
        sudo mkfs.btrfs -f /mnt/btrfs.img
        sudo mount /mnt/btrfs.img /mnt/nixbld
        sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
        echo -e "[Service]\nEnvironment=TMPDIR=/mnt/nixbld" | sudo tee /etc/systemd/system/nix-daemon.service.d/btrfs.conf
        sudo systemctl daemon-reload
        sudo systemctl restart nix-daemon
        sudo df -h
