name: setup nix
description: Setup nix and cachix

inputs:
  githubToken:
    description: "Token to authenticate with GitHub"
    required: true
  cachixToken:
    description: "Token to authenticate with cachix"
    required: true

runs:
  using: "composite"
  steps:
    - name: Allow unrestricted user namespaces
      # Ubuntu 24.04 ships strict apparmor defaults, so we have to disable them to be able to call
      # unshare in the Nix sansbox without beeing root.
      shell: bash
      run: |
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl --ignore --write kernel.apparmor_restrict_unprivileged_userns=0
    - uses: cachix/install-nix-action@a809471b5c7c913aa67bec8f459a11a0decc3fce # v31.6.2
      with:
        github_access_token: ${{ inputs.githubToken }}
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: edgelesssys
        authToken: ${{ inputs.cachixToken }}
    - name: use btrfs for nix builds
      shell: bash
      run: |
        sudo df -h

        echo "Removing unwanted software... "
        mkdir empty_dir
        sudo rsync -a --delete empty_dir/ /usr/share/dotnet
        sudo rsync -a --delete empty_dir/ /usr/local/lib/android
        sudo rsync -a --delete empty_dir/ /opt/ghc
        sudo rsync -a --delete empty_dir/ /opt/hostedtoolcache/CodeQL
        echo "Docker prune..."
        sudo docker system prune --all --force
        sudo df -h

        echo "Setting up btrfs nix builder volume..."
        sudo mkdir -p /mnt/nixbld
        sudo truncate -s 20G /mnt/btrfs.img
        sudo mkfs.btrfs -f /mnt/btrfs.img
        sudo mount /mnt/btrfs.img /mnt/nixbld
        echo "build-dir = /mnt/nixbld" | sudo tee -a /etc/nix/nix.conf
        sudo systemctl restart nix-daemon
        sudo df -h
