name: setup nix
description: Setup nix and cachix

inputs:
  githubToken:
    description: "Token to authenticate with GitHub"
    required: true
  cachixToken:
    description: "Token to authenticate with cachix"
    required: true

runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
      with:
        github_access_token: ${{ inputs.githubToken }}
    - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
      with:
        name: edgelesssys
        authToken: ${{ inputs.cachixToken }}
        installCommand: nix profile install github:cachix/cachix/3a6e4a049f7cadd8894015c2488a2fa969c83c41 --accept-flake-config
