apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    # Contrast generate expects at least one Coordinator policy hash
    contrast.edgeless.systems/pod-role: coordinator
spec:
  containers:
    - name: test
      image: busybox@sha256:0000000000000000000000000000000000000000000000000000000000000000
      command: ["sh", "-c", "sleep inf"]
  restartPolicy: Always
  runtimeClassName: contrast-cc
