apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
      command: ["sh", "-c", "sleep inf"]
  restartPolicy: Always
  runtimeClassName: contrast-cc
