// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: intercom.proto

package intercom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewMeshCertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerPublicKeyHash string `protobuf:"bytes,1,opt,name=PeerPublicKeyHash,proto3" json:"PeerPublicKeyHash,omitempty"`
}

func (x *NewMeshCertRequest) Reset() {
	*x = NewMeshCertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intercom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewMeshCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMeshCertRequest) ProtoMessage() {}

func (x *NewMeshCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intercom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMeshCertRequest.ProtoReflect.Descriptor instead.
func (*NewMeshCertRequest) Descriptor() ([]byte, []int) {
	return file_intercom_proto_rawDescGZIP(), []int{0}
}

func (x *NewMeshCertRequest) GetPeerPublicKeyHash() string {
	if x != nil {
		return x.PeerPublicKeyHash
	}
	return ""
}

type NewMeshCertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert      []byte   `protobuf:"bytes,1,opt,name=Cert,proto3" json:"Cert,omitempty"`
	CertChain [][]byte `protobuf:"bytes,2,rep,name=CertChain,proto3" json:"CertChain,omitempty"`
}

func (x *NewMeshCertResponse) Reset() {
	*x = NewMeshCertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_intercom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewMeshCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMeshCertResponse) ProtoMessage() {}

func (x *NewMeshCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intercom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMeshCertResponse.ProtoReflect.Descriptor instead.
func (*NewMeshCertResponse) Descriptor() ([]byte, []int) {
	return file_intercom_proto_rawDescGZIP(), []int{1}
}

func (x *NewMeshCertResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *NewMeshCertResponse) GetCertChain() [][]byte {
	if x != nil {
		return x.CertChain
	}
	return nil
}

var File_intercom_proto protoreflect.FileDescriptor

var file_intercom_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x22, 0x42, 0x0a, 0x12, 0x4e, 0x65,
	0x77, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x11, 0x50, 0x65, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x50, 0x65, 0x65,
	0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x48, 0x61, 0x73, 0x68, 0x22, 0x47,
	0x0a, 0x13, 0x4e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x43, 0x65, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x65, 0x72,
	0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x43, 0x65,
	0x72, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x32, 0x56, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x63, 0x6f, 0x6d, 0x12, 0x4a, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x65,
	0x72, 0x74, 0x12, 0x1c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x2e, 0x4e, 0x65,
	0x77, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x2e, 0x4e, 0x65, 0x77, 0x4d,
	0x65, 0x73, 0x68, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61,
	0x74, 0x65, 0x78, 0x6f, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x2d, 0x6b, 0x62, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_intercom_proto_rawDescOnce sync.Once
	file_intercom_proto_rawDescData = file_intercom_proto_rawDesc
)

func file_intercom_proto_rawDescGZIP() []byte {
	file_intercom_proto_rawDescOnce.Do(func() {
		file_intercom_proto_rawDescData = protoimpl.X.CompressGZIP(file_intercom_proto_rawDescData)
	})
	return file_intercom_proto_rawDescData
}

var file_intercom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_intercom_proto_goTypes = []interface{}{
	(*NewMeshCertRequest)(nil),  // 0: intercom.NewMeshCertRequest
	(*NewMeshCertResponse)(nil), // 1: intercom.NewMeshCertResponse
}
var file_intercom_proto_depIdxs = []int32{
	0, // 0: intercom.Intercom.NewMeshCert:input_type -> intercom.NewMeshCertRequest
	1, // 1: intercom.Intercom.NewMeshCert:output_type -> intercom.NewMeshCertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_intercom_proto_init() }
func file_intercom_proto_init() {
	if File_intercom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_intercom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewMeshCertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_intercom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewMeshCertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_intercom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intercom_proto_goTypes,
		DependencyIndexes: file_intercom_proto_depIdxs,
		MessageInfos:      file_intercom_proto_msgTypes,
	}.Build()
	File_intercom_proto = out.File
	file_intercom_proto_rawDesc = nil
	file_intercom_proto_goTypes = nil
	file_intercom_proto_depIdxs = nil
}
