// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: intercom.proto

package intercom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Intercom_NewMeshCert_FullMethodName = "/intercom.Intercom/NewMeshCert"
)

// IntercomClient is the client API for Intercom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntercomClient interface {
	NewMeshCert(ctx context.Context, in *NewMeshCertRequest, opts ...grpc.CallOption) (*NewMeshCertResponse, error)
}

type intercomClient struct {
	cc grpc.ClientConnInterface
}

func NewIntercomClient(cc grpc.ClientConnInterface) IntercomClient {
	return &intercomClient{cc}
}

func (c *intercomClient) NewMeshCert(ctx context.Context, in *NewMeshCertRequest, opts ...grpc.CallOption) (*NewMeshCertResponse, error) {
	out := new(NewMeshCertResponse)
	err := c.cc.Invoke(ctx, Intercom_NewMeshCert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntercomServer is the server API for Intercom service.
// All implementations must embed UnimplementedIntercomServer
// for forward compatibility
type IntercomServer interface {
	NewMeshCert(context.Context, *NewMeshCertRequest) (*NewMeshCertResponse, error)
	mustEmbedUnimplementedIntercomServer()
}

// UnimplementedIntercomServer must be embedded to have forward compatible implementations.
type UnimplementedIntercomServer struct {
}

func (UnimplementedIntercomServer) NewMeshCert(context.Context, *NewMeshCertRequest) (*NewMeshCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewMeshCert not implemented")
}
func (UnimplementedIntercomServer) mustEmbedUnimplementedIntercomServer() {}

// UnsafeIntercomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntercomServer will
// result in compilation errors.
type UnsafeIntercomServer interface {
	mustEmbedUnimplementedIntercomServer()
}

func RegisterIntercomServer(s grpc.ServiceRegistrar, srv IntercomServer) {
	s.RegisterService(&Intercom_ServiceDesc, srv)
}

func _Intercom_NewMeshCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMeshCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntercomServer).NewMeshCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Intercom_NewMeshCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntercomServer).NewMeshCert(ctx, req.(*NewMeshCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Intercom_ServiceDesc is the grpc.ServiceDesc for Intercom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Intercom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intercom.Intercom",
	HandlerType: (*IntercomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewMeshCert",
			Handler:    _Intercom_NewMeshCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intercom.proto",
}
