blank_issues_enabled: true
contact_links:
  - name: Having questions or an idea to discuss?
    url: https://github.com/edgelesssys/contrast/discussions/new?category=q-a
    about: Open a discussion instead! We will be happy to help you.
