// Copied from kata-containers/src/libs/protocols/protos/confidential_data_hub.proto
// Version: 3.28.0

//
// Copyright (c) 2024 IBM
// Copyright (c) 2024 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: katacomponents.proto

package katacomponents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnsealSecretInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealSecretInput) Reset() {
	*x = UnsealSecretInput{}
	mi := &file_katacomponents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealSecretInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealSecretInput) ProtoMessage() {}

func (x *UnsealSecretInput) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealSecretInput.ProtoReflect.Descriptor instead.
func (*UnsealSecretInput) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{0}
}

func (x *UnsealSecretInput) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type UnsealSecretOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealSecretOutput) Reset() {
	*x = UnsealSecretOutput{}
	mi := &file_katacomponents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealSecretOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealSecretOutput) ProtoMessage() {}

func (x *UnsealSecretOutput) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealSecretOutput.ProtoReflect.Descriptor instead.
func (*UnsealSecretOutput) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{1}
}

func (x *UnsealSecretOutput) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type SecureMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeType    string                 `protobuf:"bytes,1,opt,name=volume_type,json=volumeType,proto3" json:"volume_type,omitempty"`
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Flags         []string               `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	MountPoint    string                 `protobuf:"bytes,4,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureMountRequest) Reset() {
	*x = SecureMountRequest{}
	mi := &file_katacomponents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureMountRequest) ProtoMessage() {}

func (x *SecureMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureMountRequest.ProtoReflect.Descriptor instead.
func (*SecureMountRequest) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{2}
}

func (x *SecureMountRequest) GetVolumeType() string {
	if x != nil {
		return x.VolumeType
	}
	return ""
}

func (x *SecureMountRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SecureMountRequest) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *SecureMountRequest) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

type SecureMountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureMountResponse) Reset() {
	*x = SecureMountResponse{}
	mi := &file_katacomponents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureMountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureMountResponse) ProtoMessage() {}

func (x *SecureMountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureMountResponse.ProtoReflect.Descriptor instead.
func (*SecureMountResponse) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{3}
}

type ImagePullRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// - `image_url`: The reference of the image to pull
	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// - `bundle_path`: The path to store the OCI bundle. This path
	// should be created by client, and initially empty. After the RPC is
	// called, a mounted `rootfs` directory under the this path. Note
	// that this path is CDH's root filesystem, not the caller's root filesystem.
	// However, usually the caller (kata-agent) and the server (CDH) runs on the same
	// root, so it's safe to use an absolute path of kata-agent.
	BundlePath    string `protobuf:"bytes,2,opt,name=bundle_path,json=bundlePath,proto3" json:"bundle_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePullRequest) Reset() {
	*x = ImagePullRequest{}
	mi := &file_katacomponents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePullRequest) ProtoMessage() {}

func (x *ImagePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePullRequest.ProtoReflect.Descriptor instead.
func (*ImagePullRequest) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{4}
}

func (x *ImagePullRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImagePullRequest) GetBundlePath() string {
	if x != nil {
		return x.BundlePath
	}
	return ""
}

type ImagePullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePullResponse) Reset() {
	*x = ImagePullResponse{}
	mi := &file_katacomponents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePullResponse) ProtoMessage() {}

func (x *ImagePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePullResponse.ProtoReflect.Descriptor instead.
func (*ImagePullResponse) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{5}
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourcePath  string                 `protobuf:"bytes,1,opt,name=ResourcePath,proto3" json:"ResourcePath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_katacomponents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{6}
}

func (x *GetResourceRequest) GetResourcePath() string {
	if x != nil {
		return x.ResourcePath
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      []byte                 `protobuf:"bytes,1,opt,name=Resource,proto3" json:"Resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_katacomponents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_katacomponents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_katacomponents_proto_rawDescGZIP(), []int{7}
}

func (x *GetResourceResponse) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_katacomponents_proto protoreflect.FileDescriptor

const file_katacomponents_proto_rawDesc = "" +
	"\n" +
	"\x14katacomponents.proto\x12\x03api\"+\n" +
	"\x11UnsealSecretInput\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\"2\n" +
	"\x12UnsealSecretOutput\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\"\xe8\x01\n" +
	"\x12SecureMountRequest\x12\x1f\n" +
	"\vvolume_type\x18\x01 \x01(\tR\n" +
	"volumeType\x12>\n" +
	"\aoptions\x18\x02 \x03(\v2$.api.SecureMountRequest.OptionsEntryR\aoptions\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\tR\x05flags\x12\x1f\n" +
	"\vmount_point\x18\x04 \x01(\tR\n" +
	"mountPoint\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13SecureMountResponse\"P\n" +
	"\x10ImagePullRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vbundle_path\x18\x02 \x01(\tR\n" +
	"bundlePath\"\x13\n" +
	"\x11ImagePullResponse\"8\n" +
	"\x12GetResourceRequest\x12\"\n" +
	"\fResourcePath\x18\x01 \x01(\tR\fResourcePath\"1\n" +
	"\x13GetResourceResponse\x12\x1a\n" +
	"\bResource\x18\x01 \x01(\fR\bResource2X\n" +
	"\x13SealedSecretService\x12A\n" +
	"\fUnsealSecret\x12\x16.api.UnsealSecretInput\x1a\x17.api.UnsealSecretOutput\"\x002X\n" +
	"\x12SecureMountService\x12B\n" +
	"\vSecureMount\x12\x17.api.SecureMountRequest\x1a\x18.api.SecureMountResponse\"\x002X\n" +
	"\x12GetResourceService\x12B\n" +
	"\vGetResource\x12\x17.api.GetResourceRequest\x1a\x18.api.GetResourceResponse\"\x002P\n" +
	"\x10ImagePullService\x12<\n" +
	"\tPullImage\x12\x15.api.ImagePullRequest\x1a\x16.api.ImagePullResponse\"\x00B9Z7github.com/edgelesssys/contrast/internal/katacomponentsb\x06proto3"

var (
	file_katacomponents_proto_rawDescOnce sync.Once
	file_katacomponents_proto_rawDescData []byte
)

func file_katacomponents_proto_rawDescGZIP() []byte {
	file_katacomponents_proto_rawDescOnce.Do(func() {
		file_katacomponents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_katacomponents_proto_rawDesc), len(file_katacomponents_proto_rawDesc)))
	})
	return file_katacomponents_proto_rawDescData
}

var file_katacomponents_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_katacomponents_proto_goTypes = []any{
	(*UnsealSecretInput)(nil),   // 0: api.UnsealSecretInput
	(*UnsealSecretOutput)(nil),  // 1: api.UnsealSecretOutput
	(*SecureMountRequest)(nil),  // 2: api.SecureMountRequest
	(*SecureMountResponse)(nil), // 3: api.SecureMountResponse
	(*ImagePullRequest)(nil),    // 4: api.ImagePullRequest
	(*ImagePullResponse)(nil),   // 5: api.ImagePullResponse
	(*GetResourceRequest)(nil),  // 6: api.GetResourceRequest
	(*GetResourceResponse)(nil), // 7: api.GetResourceResponse
	nil,                         // 8: api.SecureMountRequest.OptionsEntry
}
var file_katacomponents_proto_depIdxs = []int32{
	8, // 0: api.SecureMountRequest.options:type_name -> api.SecureMountRequest.OptionsEntry
	0, // 1: api.SealedSecretService.UnsealSecret:input_type -> api.UnsealSecretInput
	2, // 2: api.SecureMountService.SecureMount:input_type -> api.SecureMountRequest
	6, // 3: api.GetResourceService.GetResource:input_type -> api.GetResourceRequest
	4, // 4: api.ImagePullService.PullImage:input_type -> api.ImagePullRequest
	1, // 5: api.SealedSecretService.UnsealSecret:output_type -> api.UnsealSecretOutput
	3, // 6: api.SecureMountService.SecureMount:output_type -> api.SecureMountResponse
	7, // 7: api.GetResourceService.GetResource:output_type -> api.GetResourceResponse
	5, // 8: api.ImagePullService.PullImage:output_type -> api.ImagePullResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_katacomponents_proto_init() }
func file_katacomponents_proto_init() {
	if File_katacomponents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_katacomponents_proto_rawDesc), len(file_katacomponents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_katacomponents_proto_goTypes,
		DependencyIndexes: file_katacomponents_proto_depIdxs,
		MessageInfos:      file_katacomponents_proto_msgTypes,
	}.Build()
	File_katacomponents_proto = out.File
	file_katacomponents_proto_goTypes = nil
	file_katacomponents_proto_depIdxs = nil
}
