apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  annotations:
spec:
  runtimeClassName: kata-cc-isolation
  initContainers:
    - name: init-container
      image: "busybox:latest"
      command: ["/bin/true"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
  containers:
    - name: main-container
      image: "nginx:1.14.2"
      ports:
        - containerPort: 80
