// Copyright 2026 Edgeless Systems GmbH
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: extensions.proto

package extensions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extensions    []*Extension           `protobuf:"bytes,65535,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trailer) Reset() {
	*x = Trailer{}
	mi := &file_extensions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trailer) ProtoMessage() {}

func (x *Trailer) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trailer.ProtoReflect.Descriptor instead.
func (*Trailer) Descriptor() ([]byte, []int) {
	return file_extensions_proto_rawDescGZIP(), []int{0}
}

func (x *Trailer) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Extension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collateral    []byte                 `protobuf:"bytes,1,opt,name=collateral,proto3" json:"collateral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_extensions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_extensions_proto_rawDescGZIP(), []int{1}
}

func (x *Extension) GetCollateral() []byte {
	if x != nil {
		return x.Collateral
	}
	return nil
}

var File_extensions_proto protoreflect.FileDescriptor

const file_extensions_proto_rawDesc = "" +
	"\n" +
	"\x10extensions.proto\x12\"edgelesssys.contrast.tdxextensions\"Z\n" +
	"\aTrailer\x12O\n" +
	"\n" +
	"extensions\x18\xff\xff\x03 \x03(\v2-.edgelesssys.contrast.tdxextensions.ExtensionR\n" +
	"extensions\"+\n" +
	"\tExtension\x12\x1e\n" +
	"\n" +
	"collateral\x18\x01 \x01(\fR\n" +
	"collateralBLZJgithub.com/edgelesssys/contrast/internal/attestation/tdx/issuer/extensionsb\x06proto3"

var (
	file_extensions_proto_rawDescOnce sync.Once
	file_extensions_proto_rawDescData []byte
)

func file_extensions_proto_rawDescGZIP() []byte {
	file_extensions_proto_rawDescOnce.Do(func() {
		file_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_proto_rawDesc), len(file_extensions_proto_rawDesc)))
	})
	return file_extensions_proto_rawDescData
}

var file_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extensions_proto_goTypes = []any{
	(*Trailer)(nil),   // 0: edgelesssys.contrast.tdxextensions.Trailer
	(*Extension)(nil), // 1: edgelesssys.contrast.tdxextensions.Extension
}
var file_extensions_proto_depIdxs = []int32{
	1, // 0: edgelesssys.contrast.tdxextensions.Trailer.extensions:type_name -> edgelesssys.contrast.tdxextensions.Extension
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extensions_proto_init() }
func file_extensions_proto_init() {
	if File_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_proto_rawDesc), len(file_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_proto_goTypes,
		DependencyIndexes: file_extensions_proto_depIdxs,
		MessageInfos:      file_extensions_proto_msgTypes,
	}.Build()
	File_extensions_proto = out.File
	file_extensions_proto_goTypes = nil
	file_extensions_proto_depIdxs = nil
}
