---
apiVersion: v1
kind: Pod
metadata:
  name: port-forwarder
  namespace: edg-coco
spec:
  containers:
    - name: port-forwarder
      image: nixery.dev/shell/socat
      env:
        - name: LISTEN_PORT
          value: "1313"
        - name: FORWARD_HOST
          value: coordinator-kbs.edg-coco
        - name: FORWARD_PORT
          value: "1313"
      command:
        - /bin/bash
        - "-c"
        - echo Starting port-forward with socat; socat -d -d TCP-LISTEN:${LISTEN_PORT},fork TCP:${FORWARD_HOST}:${FORWARD_PORT}; echo Port-forward exited
      ports:
        - containerPort: 1313
