// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: coordapi.proto

package coordapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoordAPI_SetManifest_FullMethodName  = "/coordapi.CoordAPI/SetManifest"
	CoordAPI_GetManifests_FullMethodName = "/coordapi.CoordAPI/GetManifests"
)

// CoordAPIClient is the client API for CoordAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordAPIClient interface {
	SetManifest(ctx context.Context, in *SetManifestRequest, opts ...grpc.CallOption) (*SetManifestResponse, error)
	GetManifests(ctx context.Context, in *GetManifestsRequest, opts ...grpc.CallOption) (*GetManifestsResponse, error)
}

type coordAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordAPIClient(cc grpc.ClientConnInterface) CoordAPIClient {
	return &coordAPIClient{cc}
}

func (c *coordAPIClient) SetManifest(ctx context.Context, in *SetManifestRequest, opts ...grpc.CallOption) (*SetManifestResponse, error) {
	out := new(SetManifestResponse)
	err := c.cc.Invoke(ctx, CoordAPI_SetManifest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordAPIClient) GetManifests(ctx context.Context, in *GetManifestsRequest, opts ...grpc.CallOption) (*GetManifestsResponse, error) {
	out := new(GetManifestsResponse)
	err := c.cc.Invoke(ctx, CoordAPI_GetManifests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordAPIServer is the server API for CoordAPI service.
// All implementations must embed UnimplementedCoordAPIServer
// for forward compatibility
type CoordAPIServer interface {
	SetManifest(context.Context, *SetManifestRequest) (*SetManifestResponse, error)
	GetManifests(context.Context, *GetManifestsRequest) (*GetManifestsResponse, error)
	mustEmbedUnimplementedCoordAPIServer()
}

// UnimplementedCoordAPIServer must be embedded to have forward compatible implementations.
type UnimplementedCoordAPIServer struct {
}

func (UnimplementedCoordAPIServer) SetManifest(context.Context, *SetManifestRequest) (*SetManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetManifest not implemented")
}
func (UnimplementedCoordAPIServer) GetManifests(context.Context, *GetManifestsRequest) (*GetManifestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifests not implemented")
}
func (UnimplementedCoordAPIServer) mustEmbedUnimplementedCoordAPIServer() {}

// UnsafeCoordAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordAPIServer will
// result in compilation errors.
type UnsafeCoordAPIServer interface {
	mustEmbedUnimplementedCoordAPIServer()
}

func RegisterCoordAPIServer(s grpc.ServiceRegistrar, srv CoordAPIServer) {
	s.RegisterService(&CoordAPI_ServiceDesc, srv)
}

func _CoordAPI_SetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordAPIServer).SetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordAPI_SetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordAPIServer).SetManifest(ctx, req.(*SetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordAPI_GetManifests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordAPIServer).GetManifests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordAPI_GetManifests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordAPIServer).GetManifests(ctx, req.(*GetManifestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordAPI_ServiceDesc is the grpc.ServiceDesc for CoordAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordapi.CoordAPI",
	HandlerType: (*CoordAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetManifest",
			Handler:    _CoordAPI_SetManifest_Handler,
		},
		{
			MethodName: "GetManifests",
			Handler:    _CoordAPI_GetManifests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordapi.proto",
}
