apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
  namespace: edg-default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: workload
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workload
    spec:
      runtimeClassName: kata-cc-isolation
      initContainers:
        - name: initializer
          image: "ghcr.io/edgelesssys/contrast/initializer:latest"
          env:
            - name: COORDINATOR_HOST
              value: coordinator
          volumeMounts:
            - name: tls-certs
              mountPath: /tls-config
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 50Mi
      containers:
        - name: workload
          image: "docker.io/library/busybox:1.36.1-musl@sha256:d4707523ce6e12afdbe9a3be5ad69027150a834870ca0933baf7516dd1fe0f56"
          command:
            - /bin/sh
            - "-c"
            - echo Workload started ; while true; do sleep 60; done
          volumeMounts:
            - name: tls-certs
              mountPath: /tls-config
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 50Mi
      volumes:
        - name: tls-certs
          emptyDir: {}
