charon {
    # Log to stderr with increased verbosity for important subsystems.
    filelog {
        stderr {
            path = stderr
            flush_line = yes

            ike_name = yes

            default = 1
            ike = 2
            cfg = 2
            enc = 2
            net = 2
        }
    }

    # Disable syslog.
    syslog {
    }
}
