apiVersion: v1
kind: Pod
metadata:
  name: extract-aks-runtime
spec:
  containers:
    - command:
        - /bin/sleep
        - inf
      image: busybox:latest
      name: extract-aks-runtime
      volumeMounts:
        - mountPath: /host
          name: hostfs
          readOnly: true
  volumes:
    - hostPath:
        path: /
        type: Directory
      name: hostfs
