apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: edg-default
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-bot
      version: v11
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote-bot
        version: v11
    spec:
      containers:
        - command:
            - emojivoto-vote-bot
          env:
            - name: WEB_HOST
              value: web-svc:443
          image: docker.l5d.io/buoyantio/emojivoto-web:v11
          name: vote-bot
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              memory: 25Mi
