---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedora
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fedora
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fedora
    spec:
      containers:
        - name: fedora
          image: docker.io/fedora:41
      runtimeClassName: REPLACE_RUNTIME
