---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
    spec:
      containers:
        - name: mongodb
          image: quay.io/mongodb/mongodb-community-server@sha256:8b73733842da21b6bbb6df4d7b2449229bb3135d2ec8c6880314d88205772a11
          volumeMounts:
            - mountPath: /data/db
              name: db
            - mountPath: /data/configdb
              name: configdb
          ports:
            - containerPort: 27017
      volumes:
        - name: db
          emptyDir:
            sizeLimit: 10Mi
        - name: configdb
          emptyDir:
            sizeLimit: 10Mi
      runtimeClassName: REPLACE_RUNTIME
