---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neo4j
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neo4j
    spec:
      containers:
        - name: neo4j
          image: docker.io/neo4j@sha256:e559d4000b000c05b10110e0b0356bac6779538efebbfe9aa6af4823e8dc0eca
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /logs
              name: logs
          ports:
            - containerPort: 7474
            - containerPort: 7473
            - containerPort: 7687
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 10Mi
        - name: logs
          emptyDir:
            sizeLimit: 10Mi
      runtimeClassName: REPLACE_RUNTIME
