---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: quay.io/nginx/nginx-unprivileged@sha256:ec783757c240e99a713eba1def9a88b983a133da215f517ed2d9a6fd734c2ad1
          ports:
            - containerPort: 8080
      runtimeClassName: REPLACE_RUNTIME
