---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-bookworm
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-bookworm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-bookworm
    spec:
      containers:
        - name: redis
          image: docker.io/redis@sha256:4d08a8fc92f2ae6508cc4a622a95a75c0549f43da7c13542e8deb031e1c0b629
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 6379
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 10Mi
      runtimeClassName: REPLACE_RUNTIME
