---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-bookworm
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-bookworm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-bookworm
    spec:
      containers:
        - name: redis
          image: docker.io/redis:7.4-rc2-bookworm
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 6379
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 10Mi
      runtimeClassName: REPLACE_RUNTIME
