---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockylinux
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rockylinux
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rockylinux
    spec:
      containers:
        - name: rockylinux
          image: docker.io/rockylinux:9.3
      runtimeClassName: REPLACE_RUNTIME
