---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      containers:
        - name: traefik
          image: docker.io/traefik:v3.1.0
          ports:
            - containerPort: 80
      runtimeClassName: REPLACE_RUNTIME
