---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      containers:
        - name: traefik
          image: docker.io/traefik:sha256:24773b7a8cf711c695957a076d550b5988bad343bf6e274ade55921ad8601841
          ports:
            - containerPort: 80
      runtimeClassName: REPLACE_RUNTIME
