// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: userapi.proto

package userapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifest []byte   `protobuf:"bytes,1,opt,name=Manifest,proto3" json:"Manifest,omitempty"`
	Policies [][]byte `protobuf:"bytes,2,rep,name=Policies,proto3" json:"Policies,omitempty"`
}

func (x *SetManifestRequest) Reset() {
	*x = SetManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManifestRequest) ProtoMessage() {}

func (x *SetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManifestRequest.ProtoReflect.Descriptor instead.
func (*SetManifestRequest) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{0}
}

func (x *SetManifestRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *SetManifestRequest) GetPolicies() [][]byte {
	if x != nil {
		return x.Policies
	}
	return nil
}

type SetManifestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PEM-encoded certificate
	RootCA []byte `protobuf:"bytes,1,opt,name=RootCA,proto3" json:"RootCA,omitempty"`
	// PEM-encoded certificate
	MeshCA []byte `protobuf:"bytes,2,opt,name=MeshCA,proto3" json:"MeshCA,omitempty"`
	// Secret seed (share), encrypted with each of the recovery holders' public keys.
	SeedSharesDoc *SeedShareDocument `protobuf:"bytes,3,opt,name=SeedSharesDoc,proto3" json:"SeedSharesDoc,omitempty"`
}

func (x *SetManifestResponse) Reset() {
	*x = SetManifestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManifestResponse) ProtoMessage() {}

func (x *SetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManifestResponse.ProtoReflect.Descriptor instead.
func (*SetManifestResponse) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{1}
}

func (x *SetManifestResponse) GetRootCA() []byte {
	if x != nil {
		return x.RootCA
	}
	return nil
}

func (x *SetManifestResponse) GetMeshCA() []byte {
	if x != nil {
		return x.MeshCA
	}
	return nil
}

func (x *SetManifestResponse) GetSeedSharesDoc() *SeedShareDocument {
	if x != nil {
		return x.SeedSharesDoc
	}
	return nil
}

type SeedShareDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeedShares []*SeedShare `protobuf:"bytes,1,rep,name=SeedShares,proto3" json:"SeedShares,omitempty"`
	Salt       []byte       `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (x *SeedShareDocument) Reset() {
	*x = SeedShareDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedShareDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedShareDocument) ProtoMessage() {}

func (x *SeedShareDocument) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedShareDocument.ProtoReflect.Descriptor instead.
func (*SeedShareDocument) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{2}
}

func (x *SeedShareDocument) GetSeedShares() []*SeedShare {
	if x != nil {
		return x.SeedShares
	}
	return nil
}

func (x *SeedShareDocument) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type SeedShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey     string `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	EncryptedSeed []byte `protobuf:"bytes,2,opt,name=EncryptedSeed,proto3" json:"EncryptedSeed,omitempty"`
}

func (x *SeedShare) Reset() {
	*x = SeedShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedShare) ProtoMessage() {}

func (x *SeedShare) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedShare.ProtoReflect.Descriptor instead.
func (*SeedShare) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{3}
}

func (x *SeedShare) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SeedShare) GetEncryptedSeed() []byte {
	if x != nil {
		return x.EncryptedSeed
	}
	return nil
}

type GetManifestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetManifestsRequest) Reset() {
	*x = GetManifestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetManifestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestsRequest) ProtoMessage() {}

func (x *GetManifestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestsRequest.ProtoReflect.Descriptor instead.
func (*GetManifestsRequest) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{4}
}

type GetManifestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifests [][]byte `protobuf:"bytes,1,rep,name=Manifests,proto3" json:"Manifests,omitempty"`
	Policies  [][]byte `protobuf:"bytes,2,rep,name=Policies,proto3" json:"Policies,omitempty"`
	// PEM-encoded certificate
	RootCA []byte `protobuf:"bytes,3,opt,name=RootCA,proto3" json:"RootCA,omitempty"`
	// PEM-encoded certificate
	MeshCA []byte `protobuf:"bytes,4,opt,name=MeshCA,proto3" json:"MeshCA,omitempty"`
}

func (x *GetManifestsResponse) Reset() {
	*x = GetManifestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetManifestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestsResponse) ProtoMessage() {}

func (x *GetManifestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestsResponse.ProtoReflect.Descriptor instead.
func (*GetManifestsResponse) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{5}
}

func (x *GetManifestsResponse) GetManifests() [][]byte {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *GetManifestsResponse) GetPolicies() [][]byte {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *GetManifestsResponse) GetRootCA() []byte {
	if x != nil {
		return x.RootCA
	}
	return nil
}

func (x *GetManifestsResponse) GetMeshCA() []byte {
	if x != nil {
		return x.MeshCA
	}
	return nil
}

type RecoverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed []byte `protobuf:"bytes,1,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Salt []byte `protobuf:"bytes,2,opt,name=Salt,proto3" json:"Salt,omitempty"`
}

func (x *RecoverRequest) Reset() {
	*x = RecoverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverRequest) ProtoMessage() {}

func (x *RecoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverRequest.ProtoReflect.Descriptor instead.
func (*RecoverRequest) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{6}
}

func (x *RecoverRequest) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *RecoverRequest) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type RecoverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecoverResponse) Reset() {
	*x = RecoverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverResponse) ProtoMessage() {}

func (x *RecoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverResponse.ProtoReflect.Descriptor instead.
func (*RecoverResponse) Descriptor() ([]byte, []int) {
	return file_userapi_proto_rawDescGZIP(), []int{7}
}

var File_userapi_proto protoreflect.FileDescriptor

var file_userapi_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x22, 0x4c, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x52, 0x6f, 0x6f, 0x74, 0x43, 0x41, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x41,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x41, 0x12, 0x40,
	0x0a, 0x0d, 0x53, 0x65, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x44, 0x6f, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0d, 0x53, 0x65, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x44, 0x6f, 0x63,
	0x22, 0x5b, 0x0a, 0x11, 0x53, 0x65, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x53, 0x65, 0x65, 0x64, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x0a, 0x53,
	0x65, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x22, 0x4f, 0x0a,
	0x09, 0x53, 0x65, 0x65, 0x64, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x65, 0x65, 0x64, 0x22, 0x15,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x09, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x74,
	0x43, 0x41, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x41,
	0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x41, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x4d, 0x65, 0x73, 0x68, 0x43, 0x41, 0x22, 0x38, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x65,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x61, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x61,
	0x6c, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xde, 0x01, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x41, 0x50,
	0x49, 0x12, 0x48, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x6c, 0x65, 0x73, 0x73, 0x73, 0x79, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_userapi_proto_rawDescOnce sync.Once
	file_userapi_proto_rawDescData = file_userapi_proto_rawDesc
)

func file_userapi_proto_rawDescGZIP() []byte {
	file_userapi_proto_rawDescOnce.Do(func() {
		file_userapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_userapi_proto_rawDescData)
	})
	return file_userapi_proto_rawDescData
}

var file_userapi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_userapi_proto_goTypes = []any{
	(*SetManifestRequest)(nil),   // 0: userapi.SetManifestRequest
	(*SetManifestResponse)(nil),  // 1: userapi.SetManifestResponse
	(*SeedShareDocument)(nil),    // 2: userapi.SeedShareDocument
	(*SeedShare)(nil),            // 3: userapi.SeedShare
	(*GetManifestsRequest)(nil),  // 4: userapi.GetManifestsRequest
	(*GetManifestsResponse)(nil), // 5: userapi.GetManifestsResponse
	(*RecoverRequest)(nil),       // 6: userapi.RecoverRequest
	(*RecoverResponse)(nil),      // 7: userapi.RecoverResponse
}
var file_userapi_proto_depIdxs = []int32{
	2, // 0: userapi.SetManifestResponse.SeedSharesDoc:type_name -> userapi.SeedShareDocument
	3, // 1: userapi.SeedShareDocument.SeedShares:type_name -> userapi.SeedShare
	0, // 2: userapi.UserAPI.SetManifest:input_type -> userapi.SetManifestRequest
	4, // 3: userapi.UserAPI.GetManifests:input_type -> userapi.GetManifestsRequest
	6, // 4: userapi.UserAPI.Recover:input_type -> userapi.RecoverRequest
	1, // 5: userapi.UserAPI.SetManifest:output_type -> userapi.SetManifestResponse
	5, // 6: userapi.UserAPI.GetManifests:output_type -> userapi.GetManifestsResponse
	7, // 7: userapi.UserAPI.Recover:output_type -> userapi.RecoverResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_userapi_proto_init() }
func file_userapi_proto_init() {
	if File_userapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userapi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SetManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userapi_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetManifestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userapi_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SeedShareDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userapi_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SeedShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userapi_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetManifestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userapi_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetManifestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userapi_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RecoverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userapi_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RecoverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userapi_proto_goTypes,
		DependencyIndexes: file_userapi_proto_depIdxs,
		MessageInfos:      file_userapi_proto_msgTypes,
	}.Build()
	File_userapi_proto = out.File
	file_userapi_proto_rawDesc = nil
	file_userapi_proto_goTypes = nil
	file_userapi_proto_depIdxs = nil
}
