#
# This config checks external links.
# It doesn't check the fragments of external links, as it isn't able to relyably detect them
# from sites like GitHub.
#

no_progress = true
cache = false
include_fragments = false
retry_wait_time = 20
fallback_extensions = ["md", "html"]
exclude = [
    '^https://mysql\.com/', # returns 403
    '^http(s)?://localhost',
    '^https://github\.com/edgelesssys/contrast/(settings|deployments)', # not public
    '^https://github\.com/edgelesssys/nix-remote-builders', # not public
    '^https://.*\.hashicorp\.com', # strict bot protection
    '^https://.*\.medium\.com', # strict bot protection
    '^https://www\.intel\.com/content/www/us/en/content-details/865802/intel-tdx-module-abi-specification\.html$', # version from 2025-09-01 is bot protected
    '^https://www\.intel\.com/content/www/us/en/content-details/867568/intel-tdx-module-base-architecture-specification\.html$' # version from 2025-10-21 is bot protected
]
exclude_path = [
    "dev-docs/frozen",
]
exclude_link_local = true

# lychee in-run caching is bugged
# https://github.com/lycheeverse/lychee/issues/1593
threads = 1
max_concurrency = 1

# This is necessary such that lychee can find static pages.
# All other links should be relative anyway!
root_dir = "./docs/static"
