name: bump version
description: Bump the projects main version and commit the change

inputs:
  version:
    description: "Version to bump to"
    required: true
  commit:
    description: Whether to commit the change
    required: false
  working-directory:
    description: "Working directory"
    required: false
    default: "."

outputs:
  commit-msg:
    description: "Commit message"
    value: ${{ steps.bump-version.outputs.commit-msg }}

runs:
  using: "composite"
  steps:
    - name: Bump version
      id: bump-version
      shell: bash
      env:
        INPUTS_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUTS_VERSION: ${{ inputs.version }}
        INPUTS_COMMIT: ${{ inputs.commit }}
      run: |
        cd ${INPUTS_WORKING_DIRECTORY}

        current=$(<version.txt)
        echo -n "${INPUTS_VERSION}" > version.txt

        commit_msg="flake: ${current} -> ${INPUTS_VERSION}"
        echo "commit-msg=${commit_msg}" | tee -a "$GITHUB_OUTPUT"

        if [[ "${INPUTS_COMMIT}" == "false" ]]; then
          exit 0
        fi

        git config --global user.name "edgelessci"
        git config --global user.email "edgelessci@users.noreply.github.com"
        git add version.txt
        git diff --staged --quiet || git commit -m "${commit_msg}"
        git push origin "$(git rev-parse --abbrev-ref HEAD)"
