

# This file was *autogenerated* from the file something.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff = Integer(0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff); _sage_const_0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc = Integer(0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc); _sage_const_0xb3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef = Integer(0xb3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef); _sage_const_0xaa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7 = Integer(0xaa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7); _sage_const_0x3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f = Integer(0x3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f); _sage_const_0xffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973 = Integer(0xffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973); _sage_const_0x1 = Integer(0x1); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_77492214967865460963471699751820070564084647936440628989923671088450960649501 = Integer(77492214967865460963471699751820070564084647936440628989923671088450960649501)#!/usr/bin/env sage


import hashlib

# ECDSA Signature without private key

# An ECDSA signature without prior commitment to the signer's key
# does not prove that the signer knows the private key
# of the pubkey for which the signature validates.

# A short demonstration:

"""
# Setup secp256k1 curve:
p = 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f      # prime
n = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141      # order of the curve
Fn = FiniteField(n)                                                         # Finite field over n
secp256k1 = EllipticCurve( GF(p), [0, 7] )

# G base point
G = secp256k1.point( (0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798, 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8) )
"""

# Setup P-384 curve:
p = _sage_const_0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff 
K = GF(p)
a = K(_sage_const_0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc )
b = K(_sage_const_0xb3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef )
E = EllipticCurve(K, (a, b))
G = E(_sage_const_0xaa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7 , _sage_const_0x3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f )
E.set_order(_sage_const_0xffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973  * _sage_const_0x1 )
n = _sage_const_0xffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973 
Fn = FiniteField(n)


# Helper functions:

# Calculate hash of message for signing
def get_message_hash(msg):
    # hash with sha256 and encode to UTF-8
    msgHashAsHexString = hashlib.sha256(msg.encode(encoding = 'UTF-8')).hexdigest()
    # return hash value as Integer
    return Integer('0x' + msgHashAsHexString)

# ecdsa signature verification
def ecdsa_verify(pub_key, msg, r, s):
    w = ZZ( _sage_const_1 / Fn(s) )                        # = 1/s
    u1 = get_message_hash(msg) * w            # u1 = hash_of_message * 1/s
    u2 = r * w
    P1 = Integer(u1) * G                      # G is base point
    P2 = Integer(u2) * pub_key                # pub_key is public key for which the signature should validate
    X = P1 + P2
    (x, y) = X.xy()
    v = Fn(x)
    print(v == r)
    return v == r




#
# MESSAGE to sign:  :)
#
message = 'message'



# an ECDSA signature consists of 2 scalar values: (r, s)
# Let's generate a completely RANDOM signature:

#
# Choose a random x coordinate r until we find one, which also has a point on the curve:
#
found_a_point = False
i = _sage_const_1 
while found_a_point == False:

    # create random r, will be part of the signature (r, s)
    r = i              # is an x coordinate, thus upper bound p
    i = i + _sage_const_1 

    # check if there is a point at this x-coord
    found_a_point = E.is_x_coord(r)

R = E.lift_x(Integer(r))       # get the point R at x-coordinate r

print(R.xy()[_sage_const_0 ])
print(R.xy()[_sage_const_1 ])
print(E.is_on_curve(R.xy()[_sage_const_0 ], R.xy()[_sage_const_1 ]))

#
# Generate a random s
#
s = _sage_const_1       # is used in point multiplication, thus upper bound n




#
# Our signature for the message aboce is now:  (r, s)
#
print('Our message: ' + message)
print('Our (randomly generated) ECDSA Signature:')
print('r: ' + str(r))
print('s: ' + str(s))
print()


#
# And now let's calculate the public key for which this random signature will validate:
#   Q   =  (sR - hG)/r
#

h = get_message_hash(message)
h = _sage_const_77492214967865460963471699751820070564084647936440628989923671088450960649501 

Q = (s*R - h*G)  *  ZZ( _sage_const_1  / Fn(r) )

assert Q == (s*R *  ZZ( _sage_const_1  / Fn(r) ) - h*G *  ZZ( _sage_const_1  / Fn(r) ))
print("left:", s*R *  ZZ( _sage_const_1  / Fn(r) ) )
print("right:", h*G *  ZZ( _sage_const_1  / Fn(r) ) )
print("r inv:", ZZ( _sage_const_1  / Fn(r) ))

print("u1", s *  ZZ( _sage_const_1  / Fn(r) ))
print("u2", (- h * ZZ( _sage_const_1  / Fn(r) )) % n)

u1G = (- h *  ZZ( _sage_const_1  / Fn(r) )) * G
print("u1 G x", str(Q.xy()[_sage_const_0 ]))
print("u1 G y", str(Q.xy()[_sage_const_1 ]))

# RESULT:
print('And here is the pubkey for which this signature will validate:')
print('x coordinate: ' + str(Q.xy()[_sage_const_0 ]))
print('y coordinate: ' + str(Q.xy()[_sage_const_1 ]))
print()
print('Voila.. :-)')
print()
print('Does the signature verify? ...')
ecdsa_verify(Q, message, r, s)




# Sample output:

#  Our message: I am Satoshi, because we all are Satoshi :-)
#  Our (randomly generated) ECDSA Signature:
#  s: 24828058834046652854540677321878462375477002606677988961933119664452896577927
#  r: 104150767398129614233917872756744768266909588448171424309616024326744528822140
#
#  And here is the pubkey for which this signature will validate:
#  x coordinate: 78105301398590714238102023061657833145875102847999004320934470842361111461126
#  y coordinate: 66537312592386171185922156484664526796876351425099945787863334980961115997865
#
#  Voila.. :-)
#
#  Does the signature verify? ...
#  True

