// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: imagestore.proto
package api

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type SecureMountServiceService interface {
	SecureMount(context.Context, *SecureMountRequest) (*SecureMountResponse, error)
}

func RegisterSecureMountServiceService(srv *ttrpc.Server, svc SecureMountServiceService) {
	srv.RegisterService("api.SecureMountService", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"SecureMount": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req SecureMountRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.SecureMount(ctx, &req)
			},
		},
	})
}

type securemountserviceClient struct {
	client *ttrpc.Client
}

func NewSecureMountServiceClient(client *ttrpc.Client) SecureMountServiceService {
	return &securemountserviceClient{
		client: client,
	}
}

func (c *securemountserviceClient) SecureMount(ctx context.Context, req *SecureMountRequest) (*SecureMountResponse, error) {
	var resp SecureMountResponse
	if err := c.client.Call(ctx, "api.SecureMountService", "SecureMount", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
