apiVersion: v1
kind: Namespace
metadata:
  name: maintenance-cleanup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-sa
  namespace: maintenance-cleanup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanup-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["list"]
  - apiGroups: ["node.k8s.io"]
    resources: ["runtimeclasses"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cleanup-binding
subjects:
  - kind: ServiceAccount
    name: cleanup-sa
    namespace: maintenance-cleanup
roleRef:
  kind: ClusterRole
  name: cleanup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-maintenance
  namespace: maintenance-cleanup
spec:
  template:
    metadata:
      name: cleanup-maintenance
    spec:
      serviceAccountName: cleanup-sa
      containers:
        - name: cleanup
          image: "@@REPLACE_IMAGE@@"
          imagePullPolicy: Always
          env:
            - name: HOST_MOUNT
              value: /host
            - name: CONFIG
              value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
            - name: SNAPSHOTTER
              value: nydus
          volumeMounts:
            - name: host-mount
              mountPath: /host
      volumes:
        - name: host-mount
          hostPath:
            path: /
            type: Directory
      restartPolicy: OnFailure
