apiVersion: v1
kind: Namespace
metadata:
  name: maintenance-namespace-cleanup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-cleanup-sa
  namespace: maintenance-namespace-cleanup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-cleanup-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-cleanup-binding
subjects:
  - kind: ServiceAccount
    name: namespace-cleanup-sa
    namespace: maintenance-namespace-cleanup
roleRef:
  kind: ClusterRole
  name: namespace-cleanup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-cleanup
  namespace: maintenance-namespace-cleanup
spec:
  schedule: "*/15 * * * *" # Every 15 minutes
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: namespace-cleanup-sa
          containers:
            - name: namespace-cleanup
              image: "@@REPLACE_IMAGE@@"
              command: ["cleanup-namespaces"]
          restartPolicy: Never
