apiVersion: v1
kind: Namespace
metadata:
  name: maintenance-containerd-cleanup
---
apiVersion: batch/v1
kind: Job
metadata:
  name: containerd-cleanup-maintenance
  namespace: maintenance-containerd-cleanup
spec:
  template:
    metadata:
      name: containerd-cleanup-maintenance
    spec:
      containers:
        - name: cleanup
          image: "@@REPLACE_IMAGE@@"
          imagePullPolicy: Always
          command: ["cleanup-containerd"]
          volumeMounts:
            - name: host-mount
              mountPath: /host
      volumes:
        - name: host-mount
          hostPath:
            path: /
            type: Directory
      restartPolicy: OnFailure
