apiVersion: v1
kind: Namespace
metadata:
  name: maintenance-nix-gc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nix-garbage-collection
  namespace: maintenance-nix-gc
spec:
  template:
    metadata:
      name: nix-garbage-collection
    spec:
      hostPID: true
      containers:
        - name: nix-garbage-collection
          image: "@@REPLACE_IMAGE@@"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: ["nix-gc"]
          volumeMounts:
            - name: host-mount
              mountPath: /host
      volumes:
        - name: host-mount
          hostPath:
            path: /
            type: Directory
      restartPolicy: OnFailure
