apiVersion: v1
kind: Namespace
metadata:
  name: maintenance-nix-gc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nix-garbage-collection
  namespace: maintenance-nix-gc
spec:
  template:
    metadata:
      name: nix-garbage-collection
    spec:
      hostPID: true
      containers:
        - name: nix-garbage-collection
          image: "@@REPLACE_IMAGE@@"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command:
            - /bin/sh
            - -c
            - nsenter --target 1 --mount -- /root/.nix-profile/bin/nix store gc
      restartPolicy: OnFailure
