kind: ServiceAccount
apiVersion: v1
metadata:
  name: voting
  namespace: edg-default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: edg-default
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voting-svc
      version: v11
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voting-svc
        version: v11
    spec:
      runtimeClassName: kata-cc-isolation
      initContainers:
        - name: initializer
          image: "ghcr.io/edgelesssys/nunki/initializer:latest"
          imagePullPolicy: Always
          env:
            - name: COORDINATOR_HOST
              value: coordinator
          volumeMounts:
            - name: tls-certs
              mountPath: /tls-config
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 50Mi
      serviceAccountName: voting
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
            - name: PROM_PORT
              value: "8801"
            - name: EDG_CERT_PATH
              value: /tls-config/certChain.pem
            - name: EDG_CA_PATH
              value: /tls-config/MeshCACert.pem
            - name: EDG_KEY_PATH
              value: /tls-config/key.pem
          image: ghcr.io/3u13r/emojivoto-voting-svc:coco-1
          imagePullPolicy: Always
          name: voting-svc
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8801
              name: prom
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              memory: 50Mi
          volumeMounts:
            - name: tls-certs
              mountPath: /tls-config
      volumes:
        - name: tls-certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: edg-default
spec:
  selector:
    app.kubernetes.io/name: voting-svc
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: prom
      port: 8801
      targetPort: 8801
