apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: @@NAMESPACE@@
spec:
  selector:
    matchLabels:
      name: log-collector
  template:
    metadata:
      labels:
        name: log-collector
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: log-collector
          image: docker.io/ubuntu:oracular # TODO(miampf): Replace with non docker.io image
          volumeMounts:
            - mountPath: /logs
              name: log-volume
              readOnly: true
          command:
            - /usr/bin/bash
            - -c
            - |
              # TODO(miampf): Prepare an image that already has required tools installed
              apt-get update && apt-get install -y inotify-tools ncompress
              mkdir /export
              inotifywait -m /logs -r -e create -e moved_to |
                while read path action file; do
                  echo "DEBUG: $path; $action; $file"
                  filepath="$path$file"
                  echo "DEBUG: $filepath"
                  if [[ -f "$filepath" ]]; then
                    echo "$filepath was created."
                    mkdir -p "/export$path"
                    tail --follow=name -v "$filepath" | compress > "/export$filepath.Z" &
                  fi
                done
      volumes:
        - name: log-volume
          # mount the nodes logs to the container
          hostPath:
            path: /var/log/pods
            type: Directory
