apiVersion: v1
kind: Namespace
metadata:
  name: debugging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-network
  namespace: debugging
  labels:
    k8s-app: pod-network
spec:
  selector:
    matchLabels:
      name: pod-network
  template:
    metadata:
      labels:
        name: pod-network
    spec:
      runtimeClassName: kata-remote
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: host-ns
        image: nicolaka/netshoot
        command:
          - /bin/bash
          - -c
          - exec sleep inf
        securityContext:
          privileged: true
