name: cleanup azure ci resources

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * 4' # At 04:15 on Thursday.
  pull_request:
    paths:
      - .github/workflows/cleanup-azure-ci-resources.yml
      - packages/by-name/azure-ci-rg-cleanup

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup_nix
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Login to Azure
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
        with:
          creds: ${{ secrets.CONTRAST_CI_INFRA_AZURE }}
      - name: Cleanup Azure CI resources
        run: |
          nix run .#azure-ci-rg-cleanup
