name: recreate ci cluster

on:
  workflow_dispatch:

env:
  azure_resource_group: nunki-ci

jobs:
  recreate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: edgelesssys
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Login to Azure
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          creds: ${{ secrets.NUNKI_CI_INFRA_AZURE }}
      - name: Cleanup .azure dir
        run: |
          rm $HOME/.azure/{commandIndex.json,versionCheck.json}
      - name: Destroy existing CI cluster
        continue-on-error: true
        run: |
          nix run .#destroy-coco-aks -- --name="$azure_resource_group"
      - name: Create CI cluster
        run: |
          nix run .#create-coco-aks -- --name="$azure_resource_group"
