name: recreate ci cluster

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # 0:00 on Sundays

env:
  azure_resource_group: contrast-ci

jobs:
  recreate:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup_nix
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - name: Login to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          creds: ${{ secrets.CONTRAST_CI_INFRA_AZURE }}
      - name: Cleanup .azure dir
        run: |
          # TODO(burgerdev): Check whether this step is still needed.
          rm -f "$HOME"/.azure/{commandIndex.json,versionCheck.json}
      - name: Destroy existing CI cluster
        continue-on-error: true
        run: |
          nix run .#scripts.destroy-coco-aks -- --name="$azure_resource_group"
      - name: Create CI cluster
        run: |
          nix run .#scripts.create-coco-aks -- --name="$azure_resource_group"
      - name: Deploy sync server
        run: |
          kubectl apply -f https://raw.githubusercontent.com/katexochen/sync/cf49dc9664f70a1b00e3febb427b9e817f8da68b/server/deployment.yml
          kubectl rollout status statefulset/sync --timeout=5m
      - name: Create fifo
        run: |
          kubectl wait --for=jsonpath='{.status.loadBalancer.ingress[0].ip}' --timeout=5m svc/sync
          nix run .#scripts.renew-sync-fifo
