name: recreate ci cluster

on:
  workflow_dispatch:

env:
  azure_resource_group: contrast-ci

jobs:
  recreate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: ./.github/actions/setup_nix
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Login to Azure
        uses: azure/login@6b2456866fc08b011acb422a92a4aa20e2c4de32 # v2.1.0
        with:
          creds: ${{ secrets.CONTRAST_CI_INFRA_AZURE }}
      - name: Cleanup .azure dir
        run: |
          rm $HOME/.azure/{commandIndex.json,versionCheck.json}
      - name: Destroy existing CI cluster
        continue-on-error: true
        run: |
          nix run .#scripts.destroy-coco-aks -- --name="$azure_resource_group"
      - name: Create CI cluster
        run: |
          nix run .#scripts.create-coco-aks -- --name="$azure_resource_group"
