name: e2e test runtime-rs

on:
  pull_request:
    paths:
      - overlays/sets/runtime-rs.nix
      - packages/by-name/kata/runtime/**
      - packages/by-name/kata/runtime-rs/**
      - e2e/runtime-rs-tmp/**

jobs:
  tests:
    strategy:
      matrix:
        platform:
          - name: Metal-QEMU-SNP
            runner: SNP
            self-hosted: true
          - name: Metal-QEMU-TDX
            runner: TDX
            self-hosted: true
          - name: Metal-QEMU-SNP-GPU
            runner: SNP-GPU
            self-hosted: true
          - name: Metal-QEMU-TDX-GPU
            runner: TDX-GPU
            self-hosted: true
        test-name:
          - runtime-rs-tmp
      fail-fast: false
    name: "${{ matrix.platform.name }}"
    uses: ./.github/workflows/e2e.yml
    with:
      skip-undeploy: false
      test-name: ${{ matrix.test-name }}
      platform: ${{ matrix.platform.name }}
      runner: ${{ matrix.platform.runner }}
      self-hosted: ${{ matrix.platform.self-hosted }}
      debug-shell: true
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      NUNKI_CI_COMMIT_PUSH_PR: ${{ secrets.NUNKI_CI_COMMIT_PUSH_PR }}
      TEAMS_CI_WEBHOOK: ${{ secrets.TEAMS_CI_WEBHOOK }}
      CONTRAST_GHCR_READ: ${{ secrets.CONTRAST_GHCR_READ }}
    permissions:
      contents: read
      packages: write
