name: e2e test nightly

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GITHUB_TOKEN_IN:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
      NUNKI_CI_COMMIT_PUSH_PR:
        required: true
      TEAMS_CI_WEBHOOK:
        required: true
      CONTRAST_GHCR_READ:
        required: true

jobs:
  maintenance:
    name: maintenance
    uses: ./.github/workflows/bm_maintenance.yml
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN_IN || secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      TEAMS_CI_WEBHOOK: ${{ secrets.TEAMS_CI_WEBHOOK }}
    permissions:
      contents: read
      packages: write

  platform:
    needs: maintenance
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Metal-QEMU-SNP
            runner: SNP
            self-hosted: true
            debug-set-test-name: openssl
          - name: Metal-QEMU-TDX
            runner: TDX
            self-hosted: true
            debug-set-test-name: openssl
          - name: Metal-QEMU-SNP-GPU
            runner: SNP-GPU
            self-hosted: true
            debug-set-test-name: gpu
          - name: Metal-QEMU-TDX-GPU
            runner: TDX-GPU
            self-hosted: true
            debug-set-test-name: gpu
    name: "${{ matrix.platform.name }}"
    uses: ./.github/workflows/e2e_nightly_platform.yml
    with:
      platform-name: ${{ matrix.platform.name }}
      runner: ${{ matrix.platform.runner }}
      self-hosted: ${{ matrix.platform.self-hosted }}
      debug-set-test-name: ${{ matrix.platform.debug-set-test-name }}
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN_IN || secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      NUNKI_CI_COMMIT_PUSH_PR: ${{ secrets.NUNKI_CI_COMMIT_PUSH_PR }}
      TEAMS_CI_WEBHOOK: ${{ secrets.TEAMS_CI_WEBHOOK }}
      CONTRAST_GHCR_READ: ${{ secrets.CONTRAST_GHCR_READ }}
    permissions:
      contents: read
      packages: write
