name: e2e test nightly

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GITHUB_TOKEN_IN:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
      NUNKI_CI_COMMIT_PUSH_PR:
        required: true
      TEAMS_CI_WEBHOOK:
        required: true
      CONTRAST_GHCR_READ:
        required: true

jobs:
  build-image:
    name: "Build cleanup-bare-metal image"
    uses: ./.github/workflows/bm_build_image.yml
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN_IN || secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    permissions:
      contents: read
      packages: write

  snp-maintenance:
    name: maintenance Metal-QEMU-SNP
    needs: build-image
    uses: ./.github/workflows/bm_maintenance_platform.yml
    with:
      platform-name: Metal-QEMU-SNP
      runner: SNP
      image: ${{ needs.build-image.outputs.image }}
      is-gpu: false
    permissions:
      contents: read

  tdx-maintenance:
    name: maintenance Metal-QEMU-TDX
    needs: build-image
    uses: ./.github/workflows/bm_maintenance_platform.yml
    with:
      platform-name: Metal-QEMU-TDX
      runner: TDX
      image: ${{ needs.build-image.outputs.image }}
      is-gpu: false
    permissions:
      contents: read

  snp-gpu-maintenance:
    name: maintenance Metal-QEMU-SNP-GPU
    needs: build-image
    uses: ./.github/workflows/bm_maintenance_platform.yml
    with:
      platform-name: Metal-QEMU-SNP-GPU
      runner: SNP-GPU
      image: ${{ needs.build-image.outputs.image }}
      is-gpu: true
    permissions:
      contents: read

  snp-dev-maintenance:
    name: maintenance Metal-QEMU-SNP-DEV
    needs: build-image
    uses: ./.github/workflows/bm_maintenance_platform.yml
    with:
      platform-name: Metal-QEMU-SNP-DEV
      runner: DEV
      image: ${{ needs.build-image.outputs.image }}
      is-gpu: false
    permissions:
      contents: read

  tdx-gpu-maintenance:
    name: maintenance Metal-QEMU-TDX-GPU
    needs: build-image
    uses: ./.github/workflows/bm_maintenance_platform.yml
    with:
      platform-name: Metal-QEMU-TDX-GPU
      runner: TDX-GPU
      image: ${{ needs.build-image.outputs.image }}
      is-gpu: true
    permissions:
      contents: read

  snp:
    name: Metal-QEMU-SNP
    needs: snp-maintenance
    uses: ./.github/workflows/e2e_nightly_platform.yml
    with:
      platform-name: Metal-QEMU-SNP
      runner: SNP
      self-hosted: true
      debug-set-test-name: openssl
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN_IN || secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      NUNKI_CI_COMMIT_PUSH_PR: ${{ secrets.NUNKI_CI_COMMIT_PUSH_PR }}
      TEAMS_CI_WEBHOOK: ${{ secrets.TEAMS_CI_WEBHOOK }}
      CONTRAST_GHCR_READ: ${{ secrets.CONTRAST_GHCR_READ }}
    permissions:
      contents: read
      packages: write

  tdx:
    name: Metal-QEMU-TDX
    needs: tdx-maintenance
    uses: ./.github/workflows/e2e_nightly_platform.yml
    with:
      platform-name: Metal-QEMU-TDX
      runner: TDX
      self-hosted: true
      debug-set-test-name: openssl
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN_IN || secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      NUNKI_CI_COMMIT_PUSH_PR: ${{ secrets.NUNKI_CI_COMMIT_PUSH_PR }}
      TEAMS_CI_WEBHOOK: ${{ secrets.TEAMS_CI_WEBHOOK }}
      CONTRAST_GHCR_READ: ${{ secrets.CONTRAST_GHCR_READ }}
    permissions:
      contents: read
      packages: write

  snp-gpu:
    name: Metal-QEMU-SNP-GPU
    needs: snp-gpu-maintenance
    uses: ./.github/workflows/e2e_nightly_platform.yml
    with:
      platform-name: Metal-QEMU-SNP-GPU
      runner: SNP-GPU
      self-hosted: true
      debug-set-test-name: gpu
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN_IN || secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      NUNKI_CI_COMMIT_PUSH_PR: ${{ secrets.NUNKI_CI_COMMIT_PUSH_PR }}
      TEAMS_CI_WEBHOOK: ${{ secrets.TEAMS_CI_WEBHOOK }}
      CONTRAST_GHCR_READ: ${{ secrets.CONTRAST_GHCR_READ }}
    permissions:
      contents: read
      packages: write

  tdx-gpu:
    name: Metal-QEMU-TDX-GPU
    needs: tdx-gpu-maintenance
    uses: ./.github/workflows/e2e_nightly_platform.yml
    with:
      platform-name: Metal-QEMU-TDX-GPU
      runner: TDX-GPU
      self-hosted: true
      debug-set-test-name: gpu
    secrets:
      GITHUB_TOKEN_IN: ${{ secrets.GITHUB_TOKEN_IN || secrets.GITHUB_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      NUNKI_CI_COMMIT_PUSH_PR: ${{ secrets.NUNKI_CI_COMMIT_PUSH_PR }}
      TEAMS_CI_WEBHOOK: ${{ secrets.TEAMS_CI_WEBHOOK }}
      CONTRAST_GHCR_READ: ${{ secrets.CONTRAST_GHCR_READ }}
    permissions:
      contents: read
      packages: write

  notify-teams:
    name: "Notify teams channel of failure"
    runs-on: ubuntu-24.04
    needs:
      - build-image
      - snp-maintenance
      - tdx-maintenance
      - snp-gpu-maintenance
      - snp-dev-maintenance
      - tdx-gpu-maintenance
      - snp
      - tdx
      - snp-gpu
      - tdx-gpu
    if: always() && github.event_name == 'schedule' && github.run_attempt == 1
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Get JSON output
        id: get-json
        env:
          IMAGE_BUILD_RESULT: ${{ needs.build-image.outputs.image }}
          UPDATE_RESOURCES_SNP: ${{ needs.snp-maintenance.outputs.update-resources }}
          UPDATE_RESOURCES_TDX: ${{ needs.tdx-maintenance.outputs.update-resources }}
          UPDATE_RESOURCES_SNP_GPU: ${{ needs.snp-gpu-maintenance.outputs.update-resources }}
          UPDATE_RESOURCES_SNP_DEV: ${{ needs.snp-dev-maintenance.outputs.update-resources }}
          UPDATE_RESOURCES_TDX_GPU: ${{ needs.tdx-gpu-maintenance.outputs.update-resources }}
          CLEANUP_SNP: ${{ needs.snp-maintenance.outputs.cleanup }}
          CLEANUP_TDX: ${{ needs.tdx-maintenance.outputs.cleanup }}
          CLEANUP_SNP_GPU: ${{ needs.snp-gpu-maintenance.outputs.cleanup }}
          CLEANUP_SNP_DEV: ${{ needs.snp-dev-maintenance.outputs.cleanup }}
          CLEANUP_TDX_GPU: ${{ needs.tdx-gpu-maintenance.outputs.cleanup }}
          CLEANUP_CONTAINERD_SNP: ${{ needs.snp-maintenance.outputs.cleanup-containerd }}
          CLEANUP_CONTAINERD_TDX: ${{ needs.tdx-maintenance.outputs.cleanup-containerd }}
          CLEANUP_CONTAINERD_SNP_GPU: ${{ needs.snp-gpu-maintenance.outputs.cleanup-containerd }}
          CLEANUP_CONTAINERD_SNP_DEV: ${{ needs.snp-dev-maintenance.outputs.cleanup-containerd }}
          CLEANUP_CONTAINERD_TDX_GPU: ${{ needs.tdx-gpu-maintenance.outputs.cleanup-containerd }}
          NIX_GC_SNP: ${{ needs.snp-maintenance.outputs.nix-gc }}
          NIX_GC_TDX: ${{ needs.tdx-maintenance.outputs.nix-gc }}
          NIX_GC_SNP_GPU: ${{ needs.snp-gpu-maintenance.outputs.nix-gc }}
          NIX_GC_SNP_DEV: ${{ needs.snp-dev-maintenance.outputs.nix-gc }}
          NIX_GC_TDX_GPU: ${{ needs.tdx-gpu-maintenance.outputs.nix-gc }}
          GITHUB_EVENT_SCHEDULE: ${{ github.event.schedule }}
        run: |
          if [[ -z "${IMAGE_BUILD_RESULT}" ]]; then
            echo 'json=[{"title": "Job ID", "value": "build-image"}]' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          declare -a entries snp tdx snp_gpu snp_dev tdx_gpu

          [[ "${UPDATE_RESOURCES_SNP}" != "success" ]] && snp+=("update-resources")
          [[ "${CLEANUP_SNP}" != "success" ]] && snp+=("cleanup")
          [[ "${NIX_GC_SNP}" != "success" ]] && snp+=("nix-gc")

          [[ "${UPDATE_RESOURCES_TDX}" != "success" ]] && tdx+=("update-resources")
          [[ "${CLEANUP_TDX}" != "success" ]] && tdx+=("cleanup")
          [[ "${NIX_GC_TDX}" != "success" ]] && tdx+=("nix-gc")

          [[ "${UPDATE_RESOURCES_SNP_GPU}" != "success" ]] && snp_gpu+=("update-resources")
          [[ "${CLEANUP_SNP_GPU}" != "success" ]] && snp_gpu+=("cleanup")
          [[ "${NIX_GC_SNP_GPU}" != "success" ]] && snp_gpu+=("nix-gc")

          [[ "${UPDATE_RESOURCES_SNP_DEV}" != "success" ]] && snp_dev+=("update-resources")
          [[ "${CLEANUP_SNP_DEV}" != "success" ]] && snp_dev+=("cleanup")
          [[ "${NIX_GC_SNP_DEV}" != "success" ]] && snp_dev+=("nix-gc")

          [[ "${UPDATE_RESOURCES_TDX_GPU}" != "success" ]] && tdx_gpu+=("update-resources")
          [[ "${CLEANUP_TDX_GPU}" != "success" ]] && tdx_gpu+=("cleanup")
          [[ "${NIX_GC_TDX_GPU}" != "success" ]] && tdx_gpu+=("nix-gc")

          if [[ "${GITHUB_EVENT_SCHEDULE}" == "0 2 * * 5" ]]; then
            [[ "${CLEANUP_CONTAINERD_SNP}" != "success" ]] && snp+=("cleanup-containerd")
            [[ "${CLEANUP_CONTAINERD_TDX}" != "success" ]] && tdx+=("cleanup-containerd")
            [[ "${CLEANUP_CONTAINERD_SNP_GPU}" != "success" ]] && snp_gpu+=("cleanup-containerd")
            [[ "${CLEANUP_CONTAINERD_SNP_DEV}" != "success" ]] && snp_dev+=("cleanup-containerd")
            [[ "${CLEANUP_CONTAINERD_TDX_GPU}" != "success" ]] && tdx_gpu+=("cleanup-containerd")
          fi

          if [[ "${#snp[@]}" -gt 0 ]]; then
            entries+=("{\"title\": \"Metal-QEMU-SNP\", \"value\": \"$(str="${snp[*]}"; echo "${str// /, }")\"}")
          fi
          if [[ "${#tdx[@]}" -gt 0 ]]; then
            entries+=("{\"title\": \"Metal-QEMU-TDX\", \"value\": \"$(str="${tdx[*]}"; echo "${str// /, }")\"}")
          fi

          if [[ "${#snp_gpu[@]}" -gt 0 ]]; then
            entries+=("{\"title\": \"Metal-QEMU-SNP-GPU\", \"value\": \"$(str="${snp_gpu[*]}"; echo "${str// /, }")\"}")
          fi

          if [[ "${#snp_dev[@]}" -gt 0 ]]; then
            entries+=("{\"title\": \"Metal-QEMU-SNP-DEV\", \"value\": \"$(str="${snp_dev[*]}"; echo "${str// /, }")\"}")
          fi

          if [[ "${#tdx_gpu[@]}" -gt 0 ]]; then
            entries+=("{\"title\": \"Metal-QEMU-TDX-GPU\", \"value\": \"$(str="${tdx_gpu[*]}"; echo "${str// /, }")\"}")
          fi

          if [[ "${#entries[@]}" -eq 0 ]]; then
            echo "No failures detected, nothing to notify."
            exit 0
          fi

          json=$(IFS=,; echo "${entries[*]}")
          echo "json=[${json}]" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/post_to_teams
        if: ${{ steps.get-json.outputs.json != '' }}
        with:
          webhook: ${{ secrets.TEAMS_CI_WEBHOOK }}
          title: "${{ github.workflow }} failed"
          message: "workflow ${{ github.workflow }} failed"
          additionalFields: "${{ steps.get-json.outputs.json }}"
