name: links check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  pull_request:
    paths:
      - ".github/workflows/links.yml"

jobs:
  check-links:
    name: check external links
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      SET: base
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup_nix
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Run lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix run ".#${SET}.nixpkgs.lychee" -- --config tools/lychee/config-external.toml .
      - name: Save lychee cache
        uses: actions/cache/save@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
