name: publish docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**

permissions:
  contents: write

jobs:
  deploy:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./docs
      - name: Install dependencies
        working-directory: ./docs
        run: npm ci
      - name: Build website
        working-directory: ./docs
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build # Build output to publish to the `gh-pages` branch
          user_name: edgelessci
          user_email: edgelessci@users.noreply.github.com
